---

- name: allow nonlocal binds
  copy: content='net.ipv4.ip_nonlocal_bind = 1\n' dest=/etc/sysctl.d/10-ip-nonlocal-bind.conf owner=root group=root mode=0644
  notify: reload sysctl

- name: install haproxy
  apt: name=haproxy state=latest
  notify: restart haproxy

- name: install haproxy.cfg
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg owner=root group=root mode=0644
  notify: restart haproxy

- name: create haproxy/conf.d
  file: dest=/etc/haproxy/conf.d state=directory owner=root group=root mode=0644

- name: replace haproxy init script
  copy: src=haproxy.init dest=/etc/init.d/haproxy owner=root group=root mode=0755
  notify: restart haproxy

- meta: flush_handlers

- name: ensure haproxy is started
  service: name=haproxy state=started enabled=yes
