---

- name: install nrpe
  apt: name=nagios-nrpe-server

- name: install monitoring-plugins-standard
  apt: name=monitoring-plugins-standard
  when: inventory_hostname in groups['galera']

- name: enable sudo for nrpe
  copy: content='nagios ALL=(root) NOPASSWD:ALL' dest=/etc/sudoers.d/nrpe owner=root group=root mode=0600

- name: install hw check scripts
  copy: src={{ item.script }} dest=/usr/local/bin/{{ item.script }} owner=root group=root mode=0755
  when: item.enabled
  with_items:
    - { 'script': 'check_linux_bonding.pl', 'enabled': "{{ nagios_bond }}" }
    - { 'script': 'check_swraid.py', 'enabled': "{{ nagios_mdraid }}" }
    - { 'script': check_ipmi_sensors, 'enabled': "{{ nagios_ipmi }}" }

- name: install ceph health check scripts
  copy: src={{ item }} dest=/usr/local/bin/{{ item }} owner=root group=root mode=0755
  with_items:
    - check_ceph_health
    - check_ceph_df
  when: inventory_hostname in groups['ceph_monitor']

- name: install haproxy health check scripts
  copy: src=check_haproxy_stats.pl dest=/usr/local/bin/check_haproxy_stats.pl owner=root group=root mode=0755
  when: inventory_hostname in groups['haproxy']

- name: install nrpe config
  template: src=nrpe.cfg.j2 dest=/etc/nagios/nrpe.cfg owner=root group=root mode=0644
  notify: restart nrpe

- name: install openstack nrpe config
  template: src=openstack_nrpe.cfg.j2 dest=/etc/nagios/nrpe.d/openstack_nrpe.cfg owner=root group=nagios mode=0640
  notify: restart nrpe

- meta: flush_handlers

- name: make sure nrpe is enabled and started
  service: name=nagios-nrpe-server state=started enabled=yes
