---

- name: restart designate
  service: name={{ item }} state=restarted
  with_items:
    - designate-api
    - designate-agent
    - designate-central
    - designate-producer
    - designate-worker
    - designate-mdns
