---

sahara_db_user: sahara
sahara_mysql_server: "{{ vip_mgmt }}"
sahara_db: sahara
sahara_rabbit_vhost: sahara
sahara_rabbit_user: sahara
sahara_admin_user: sahara
sahara_domain_name: "{{ keystone_domain_name }}"
sahara_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
sahara_project_name: "{{ keystone_service_project_name | default('service') }}"

sahara_syslog_use: "{{ syslog_use | default(False) }}"

sahara_debug: False

keystone_proto: "{{ (keystone_ssl | default(False)) | ternary('https', 'http') }}"
ssl_insecure: False
SSLCACertificateFileSource:
SSLCACertificateFile: "{{ (SSLCACertificateFileSource is not none and SSLCACertificateFileSource | trim != '') | ternary('/etc/ssl/certs/openstack.ca.crt','') }}"
