---

- name: restart neutron-server
  service: name=neutron-server state=restarted
  when: inventory_hostname in groups['neutron_controller']

- name: restart neutron-l3-agent
  service: name="{{ neutron_vpnaas_type | ternary('neutron-vpn-agent', 'neutron-l3-agent') }}" state=restarted
  when: inventory_hostname in groups['neutron_l3']

- name: restart neutron-dhcp-agent
  service: name=neutron-dhcp-agent state=restarted
  when: inventory_hostname in groups['neutron_l3']

- name: restart neutron-metadata-agent
  service: name=neutron-metadata-agent state=restarted
  when: inventory_hostname in groups['neutron_l3']

- name: restart neutron-lbaas-agent
  service: name=neutron-{{ neutron_lbaas_agent }}-agent state=restarted
  when: inventory_hostname in groups['neutron_l3']

- name: restart neutron-l2-agent
  service: name="neutron-{{ neutron_physical_interface_driver }}-agent" state=restarted
  when: inventory_hostname in groups['neutron_l2']

- name: reload sysctl
  command: /sbin/sysctl --system

- name: reload apparmor
  service: name=apparmor state=reloaded
