---

- name: reload systemd
  command: systemctl daemon-reload

- name: restart keystone
  service:
    name: keystone-uwsgi
    state: restarted

- name: run systemd-tmpfiles.d
  command: /bin/systemd-tmpfiles --create
