---

- name: signal apache to reload
  file: dest=/run/apache2.reload state=touch

- name: recompile python-cinder
  command: /usr/bin/pycompile -p python-cinder

- name: restart cinder-scheduler
  service: name=cinder-scheduler state=restarted
  when: inventory_hostname in groups['cinder']

- name: restart cinder-volume
  service: name={{ item }} state=restarted
  with_items:
    - cinder-volume
    - cinder-backup
  when: inventory_hostname in groups['cinder_volume']
