---

- name: signal apache to reload
  file: dest=/run/apache2.reload state=touch

- name: restart cinder-scheduler
  service: name=cinder-scheduler state=restarted
  when: inventory_hostname in groups['cinder']

- name: restart cinder-volume
  service: name={{ item }} state=restarted
  with_items:
    - cinder-volume
  when: inventory_hostname in groups['cinder_volume']

- name: restart cinder-backup
  service: name={{ item }} state=restarted
  with_items:
    - cinder-backup
  when: inventory_hostname in groups['cinder_backup']
