---

#- command: apt-get install --reinstall python-oslo.messaging python-ceilometer python-cinder

# Fixed in oslo.messaging 5.30.2
- name: patch oslo.messaging for bug 1734788
  patch: basedir=/usr/lib/python2.7/dist-packages/oslo_messaging strip=2 src=oslo.messaging.diff
  notify:
    - recompile oslo.messaging
    - restart ceilometer-agent-notification
  when: inventory_hostname in groups['ceilometer_controller']
