---

heat_db_user: heat
heat_mysql_server: "{{ vip_mgmt }}"
heat_db: heat
heat_rabbit_user: heat
heat_admin_user: heat
heat_domain_name: "{{ keystone_domain_name }}"
heat_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
heat_project_name: "{{ keystone_service_project_name | default('service') }}"

heat_user_domain: heat_user_domain
heat_domain_admin: heat_domain_admin

heat_syslog_use: "{{ syslog_use | default(False) }}"

heat_debug: False

keystone_proto: "{{ (keystone_ssl | default(False)) | ternary('https', 'http') }}"
ssl_insecure: False
SSLCACertificateFileSource:
SSLCACertificateFile: "{{ (SSLCACertificateFileSource is not none and SSLCACertificateFileSource | trim != '') | ternary('/etc/ssl/certs/openstack.ca.crt','') }}"
