# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
apt-get update
apt-get -y install python-minimal openvswitch-switch
ovs-vsctl br-exists ovs-ext || ovs-vsctl add-br ovs-ext
ovs-vsctl br-exists ovs-vlan || ovs-vsctl add-br ovs-vlan
ovs-vsctl list-ports ovs-ext | grep enp0s10 || ovs-vsctl add-port ovs-ext enp0s10
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "openstack-aio"

  # Networking
  config.vm.network :private_network, ip: "10.10.0.11"  # management
  config.vm.network :private_network, ip: "10.10.1.11"  # public
  config.vm.network :private_network, ip: "10.10.2.11", # Neutron flat ext + vlan projects
                     auto_config: false

  config.vm.provider :virtualbox do |vb|
    vb.cpus = 4
    vb.memory = "12288"
    vb.customize ["modifyvm", :id, "--nicpromisc4", "allow-all"]
  end

  config.vm.provision "shell", inline: $script

  config.vm.provision :ansible do |ansible|
    ansible.inventory_path = "../inventory/inventory.py"
    ansible.limit = "all"
    ansible.playbook = "../aio-deploy.yml"
    #ansible.verbose = "vvvv"
  end
end
