# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo "auto eth3" > /etc/network/interfaces.d/eth3.cfg
echo "iface eth3 inet manual" >> /etc/network/interfaces.d/eth3.cfg
ifup eth3
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "openstack-aio"

  # Networking
  config.vm.network :private_network, ip: "10.10.0.11"  # management
  config.vm.network :private_network, ip: "10.10.1.11"  # external
  config.vm.network :private_network, ip: "10.10.2.11", # Neutron flat network
                     auto_config: false


  config.vm.provider :virtualbox do |vb|
    vb.cpus = 4
    vb.memory = "10240"
    vb.customize ["modifyvm", :id, "--nicpromisc4", "allow-all"]
  end

  config.vm.provision "shell", inline: $script

  config.vm.provision :ansible do |ansible|
    ansible.inventory_path = "../inventory/inventory.py"
    ansible.limit = "all"
    ansible.playbook = "../aio-deploy.yml"
    #ansible.verbose = "vvvv"
  end
end
