---

- name: set up /etc/hosts
  lineinfile: dest=/etc/hosts owner=root group=root mode=0644
    regexp="^{{ hostvars[item].ip.mgmt }}\s.*$"
    line="{{ hostvars[item].ip.mgmt }} {{ item }}"
    state=present
  with_items: "{{ hosts }}"
