trove_db_user: trove
trove_mysql_server: "{{ vip_mgmt }}"
trove_db: trove
trove_rabbit_user: trove
trove_admin_user: trove
trove_domain_name: "{{ keystone_domain_name }}"
trove_project_domain_name: "{{ trove_domain_name }}"
trove_project_name: trove

trove_net_name: trove-net
trove_net_segmentation_id: 915
trove_net_type: vlan
trove_physical_network: vlan
trove_subnet_cidr: 10.20.30.0/24

trove_image_path: /etc/openstack_deploy/trove-mysql.qcow2

trove_backup_use_openssl_encryption: False
trove_backup_aes_cbc_key: "default_aes_cbc_key"

trove_syslog_use: "{{ syslog_use | default(False) }}"

nova_admin_user: nova
nova_domain_name: "{{ keystone_domain_name }}"
nova_project_name: "{{ keystone_service_project_name | default('service') }}"
nova_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"

keystone_proto: "{{ (keystone_ssl | default(False)) | ternary('https', 'http') }}"
ssl_insecure: False
