---

cloudkitty_db_user: cloudkitty
cloudkitty_mysql_server: "{{ vip_mgmt }}"
cloudkitty_db: cloudkitty
cloudkitty_rabbit_vhost: cloudkitty
cloudkitty_rabbit_user: cloudkitty
cloudkitty_admin_user: cloudkitty
cloudkitty_domain_name: "{{ keystone_domain_name }}"
cloudkitty_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
cloudkitty_project_name: "{{ keystone_service_project_name | default('service') }}"

cloudkitty_api_workers: "{{ (ansible_processor_vcpus + 1) // 2 }}"
cloudkitty_processor_workers: "{{ (ansible_processor_vcpus + 1) // 2 }}"

cloudkitty_notifications: "{{ notifications_enable | default(False) }}"

cloudkitty_syslog_use: "{{ syslog_use | default(False) }}"

cloudkitty_debug: False

keystone_proto: "{{ (keystone_ssl | default(False)) | ternary('https', 'http') }}"
os_proto: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}"
ssl_insecure: False
SSLCACertificateFileSource:
SSLCACertificateFile: "{{ (SSLCACertificateFileSource is not none and SSLCACertificateFileSource | trim != '') | ternary('/etc/ssl/certs/openstack.ca.crt','') }}"
