vip_mgmt: 10.97.36.127
vip_mgmt_cidr: 24
vip_mgmt_nic: br-vlan

vip_public: 10.97.36.127
vip_public_cidr: 24
vip_public_nic: br-vlan

keystone_internal_ip: "{{ vip_mgmt }}"
keystone_admin_ip: "{{ vip_mgmt }}"
keystone_public_ip: "{{ vip_mgmt }}"

keystone_region_name: RegionONE
keystone_domain_name: Default

neutron_flat_networks:
neutron_physical_interface_mappings: vlan:br-vlan
neutron_vlan_ranges: vlan:901:915
neutron_ha_network_type: vlan
neutron_ha_network_physical_name: vlan

trove_net_name: trove-net
trove_net_segmentation_id: 915
trove_net_type: vlan
trove_physical_network: vlan
trove_subnet_cidr: 10.20.30.0/24
trove_image_path: /etc/openstack_deploy/trove-mysql.qcow2

#ceph or lvm
cinder_backend: ceph
cinder_ceph_pool: images
cinder_ceph_user: cinder
cinder_backup_ceph_pool: backups
cinder_backup_ceph_user: cinder-backup
cinder_volume_secret_uuid: d048aa33-c46c-4573-a0c9-dd014d56e2b4

#ceph or files
glance_backend: ceph
glance_ceph_pool: images
glance_ceph_user: glance
