vip_mgmt: 10.97.36.127
vip_mgmt_cidr: 24
vip_mgmt_nic: br-vlan

vip_public: 10.97.36.127
vip_public_cidr: 24
vip_public_nic: br-vlan

keystone_internal_ip: "{{ vip_mgmt }}"
keystone_admin_ip: "{{ vip_mgmt }}"
keystone_public_ip: "{{ vip_mgmt }}"

keystone_region_name: RegionONE
keystone_domain_id: default

neutron_flat_networks:
neutron_physical_interface_mappings: vlan:br-vlan
neutron_vlan_ranges: vlan:901:915
neutron_ha_network_type: vlan
neutron_ha_network_physical_name: vlan

trove_net_name: trove-net
trove_net_segmentation_id: 915
trove_net_type: vlan
trove_physical_network: vlan
trove_subnet_cidr: 10.20.30.0/24
trove_image_path: /etc/openstack_deploy/trove-mysql.qcow2