mongodb_key:
rabbitmq_erlang_cookie:
galera_wsrep_password:
galera_clustercheck_password:
mysql_root_password:

keystone_admin_token:
keystone_db_password:
keystone_rabbit_password:

keystone_admin_password: admIn