---

panko_db_user: panko
panko_mysql_server: "{{ vip_mgmt }}"
panko_db: panko
panko_rabbit_vhost: panko
panko_rabbit_user: panko
panko_admin_user: panko
panko_domain_name: "{{ keystone_domain_name }}"
panko_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
panko_project_name: "{{ keystone_service_project_name | default('service') }}"

panko_backend: mysql

panko_syslog_use: "{{ syslog_use | default(False) }}"

panko_debug: False

mongodb_replica_set: openstack

keystone_proto: "{{ (keystone_ssl | default(False)) | ternary('https', 'http') }}"
ssl_insecure: False
SSLCACertificateFileSource:
SSLCACertificateFile: "{{ (SSLCACertificateFileSource is not none and SSLCACertificateFileSource | trim != '') | ternary('/etc/ssl/certs/openstack.ca.crt','') }}"
