---

- name: install CA certificate
  copy: src="{{ SSLCACertificateFileSource }}" dest="{{ SSLCACertificateFile }}" owner=root group=root mode=0644
  when: SSLCACertificateFile != ''

- include: swift-rings.yml
- include: swift-proxy.yml
- include: swift-storage.yml
