---

- name: ensure horizon group exists
  group: name=horizon system=yes

- name: ensure horizon user exists
  user: name=horizon group=horizon home=/usr/share/openstack-dashboard/ createhome=no shell=/bin/false system=yes

- name: ensure /etc/openstack-dashboard exists
  file: dest=/etc/openstack-dashboard owner=horizon group=horizon mode=0750 state=directory

- name: install local_settings.py
  template: src=local_settings.py.j2 dest=/etc/openstack-dashboard/local_settings.py owner=root group=horizon mode=0640
  notify: restart apache

- name: install horizon
  apt: name=openstack-dashboard

- name: install additional dashboards
  apt: name={{ item.package }}
  when: horizon_install_dashboards | bool and groups[item.service] | count > 0
  with_items:
    - { service: 'trove', package: 'python-trove-dashboard' }
    - { service: 'sahara', package: 'python-sahara-dashboard' }
    - { service: 'murano', package: 'python-murano-dashboard' }
    - { service: 'manila', package: 'python-manila-ui' }

- name: install Neutron LBaaS dashboard
  apt: name=python-neutron-lbaas-dashboard
  when:  horizon_install_dashboards | bool and neutron_lbaas_agent == 'lbaasv2'

- name: install CA certificate
  copy: src="{{ SSLCACertificateFileSource }}" dest="{{ SSLCACertificateFile }}" owner=root group=root mode=0644
  when: SSLCACertificateFile != ''
  notify: restart apache

- name: install certificates
  copy: src={{ item.src }} dest={{ item.dest }} owner=www-data group=root mode={{ item.mode }}
  with_items:
    - { src: '{{ SSLCertificateKeyFileSource | default("") }}', dest: '{{ SSLCertificateKeyFile }}', mode: '0460' }
    - { src: '{{ SSLCertificateFileSource | default("") }}', dest: '{{ SSLCertificateFile }}', mode: '0464' }
  when: item.src != ''
  notify: restart apache

- name: enable mod_ssl
  file: src=../mods-available/ssl.load dest=/etc/apache2/mods-enabled/ssl.load state=link
  when: SSLCertificateKeyFileSource is defined
  notify: restart apache

- name: enable mod_rewrite
  file: src=../mods-available/rewrite.load dest=/etc/apache2/mods-enabled/rewrite.load state=link
  notify: restart apache

- name: install ports.conf
  template: src=ports.conf.j2 dest=/etc/apache2/ports.conf owner=root group=root mode=0644
  notify: restart apache

- name: install default-ssl.conf
  template: src=default-ssl.conf.j2 dest=/etc/apache2/sites-available/default-ssl.conf owner=root group=root mode=0644
  notify: restart apache

- name: install 000-default.conf
  template: src=000-default.conf.j2 dest=/etc/apache2/sites-available/000-default.conf owner=root group=root mode=0644
  notify: restart apache

- name: enable default-ssl site
  file: src=../sites-available/default-ssl.conf dest=/etc/apache2/sites-enabled/default-ssl.conf state=link
  when: SSLCertificateKeyFileSource is defined
  notify: restart apache

- name: install openstack-dashboard.conf
  template: src=openstack-dashboard.conf.j2 dest=/etc/apache2/conf-available/openstack-dashboard.conf owner=root group=root mode=0644
  notify: restart apache

- meta: flush_handlers

- name: ensure apache is started
  service: name=apache2 state=started enabled=yes
