---

- name: ensure apache2 is installed
  apt: name={{ item }}
  with_items:
    - apache2

- name: ensure apache2 is started
  service: name=apache2 state=started enabled=yes

- name: enable proxy_http
  file: src=../mods-available/proxy_http.load dest=/etc/apache2/mods-enabled/proxy_http.load state=link
  when: inventory_hostname in groups['neutron_controller']
  notify: reload apache

- name: install site.conf
  template: src=proxy-site.conf.j2 dest=/etc/apache2/sites-available/{{ service_name }}-site.conf owner=root group=root mode=0644
  notify: reload apache

- name: enable site
  file: src=../sites-available/{{ service_name }}-site.conf dest=/etc/apache2/sites-enabled/{{ service_name }}-site.conf state=link
  notify: reload apache
