---

- name: ensure apache2 is installed
  apt:
    name:
    - apache2
    - libapache2-mod-wsgi-py3

- name: ensure mod-auth-openidc is installed
  apt: name=libapache2-mod-auth-openidc
  when: apache_oidc

- name: ensure apache2 is started
  service: name=apache2 state=started enabled=yes

- name: enable mod_ssl
  file: src=../mods-available/{{ item }} dest=/etc/apache2/mods-enabled/{{ item }} state=link
  when: SSLCertificateKeyFileSource is defined
  with_items:
    - ssl.load
    - ssl.conf
    - socache_shmcb.load
  notify: restart apache

- name: enable apache modules
  file: src=../mods-available/{{ item }}.load dest=/etc/apache2/mods-enabled/{{ item }}.load state=link
  with_items:
    - rewrite
    - proxy
    - proxy_fcgi
    - proxy_http
  notify: restart apache

- name: enable apache auth_openidc module
  file: src=../mods-available/auth_openidc.load dest=/etc/apache2/mods-enabled/auth_openidc.load state=link
  when: apache_oidc
  notify: restart apache

- name: install CA certificate
  copy: src="{{ SSLCACertificateFileSource }}" dest="{{ SSLCACertificateFile }}" owner=root group=root mode=0644
  when: SSLCACertificateFile != ''
  notify: reload apache

- name: install certificates
  copy: src={{ item.src }} dest={{ item.dest }} owner=www-data group=root mode={{ item.mode }}
  with_items:
    - { src: '{{ SSLCertificateKeyFileSource | default("") }}', dest: '{{ SSLCertificateKeyFile }}', mode: '0460' }
    - { src: '{{ SSLCertificateFileSource | default("") }}', dest: '{{ SSLCertificateFile }}', mode: '0464' }
  when: item.src != ''
  notify: reload apache

- name: create the access log for the service
  copy: content='' dest=/var/log/apache2/{{ apache_service_name }}-access.log owner=root group=adm mode=0640 force=no

- name: set permissions of the access log
  file: path=/var/log/apache2/{{ apache_service_name }}-access.log owner=root group=adm mode=0640

- name: install site.conf
  template: src=proxy-site.conf.j2 dest=/etc/apache2/sites-available/{{ apache_service_name }}-site.conf owner=root group=root mode=0644
  notify: reload apache

- name: enable site
  file: src=../sites-available/{{ apache_service_name }}-site.conf dest=/etc/apache2/sites-enabled/{{ apache_service_name }}-site.conf
    state={{ apache_service_enable | ternary('link','absent') }}
  notify: reload apache

- name: remove reload signal
  file: dest=/run/apache2.reload state=absent
  notify: reload apache
