---

- name: ensure apache2 is installed
  apt: name={{ item }}
  with_items:
    - apache2

- name: ensure apache2 is started
  service: name=apache2 state=started enabled=yes

- name: install certificates
  copy: src={{ item.src }} dest={{ item.dest }} owner=www-data group=root mode={{ item.mode }}
  with_items:
    - { src: '{{ SSLCertificateKeyFileSource | default("") }}', dest: '{{ SSLCertificateKeyFile }}', mode: '0460' }
    - { src: '{{ SSLCertificateFileSource | default("") }}', dest: '{{ SSLCertificateFile }}', mode: '0464' }
  when: item.src != ''
  notify: reload apache

- name: enable proxy_http
  file: src=../mods-available/{{ item }}.load dest=/etc/apache2/mods-enabled/{{ item }}.load state=link
  with_items:
    - proxy
    - proxy_http
  notify: reload apache

- name: install site.conf
  template: src=proxy-site.conf.j2 dest=/etc/apache2/sites-available/{{ service_name }}-site.conf owner=root group=root mode=0644
  notify: reload apache

- name: enable site
  file: src=../sites-available/{{ service_name }}-site.conf dest=/etc/apache2/sites-enabled/{{ service_name }}-site.conf state=link
  notify: reload apache
