- name: install radosgw
  apt: name={{ item }}
  with_items:
    - radosgw
    - libnss3-tools

- name: set up /etc/ceph/ceph.conf for radosgw
  ini_file: dest=/etc/ceph/ceph.conf
    section=client.radosgw.gateway
    option="{{ item.key }}"
    value="{{ item.value }}"
  with_dict:
    { "host" : "{{ inventory_hostname }}",
      "keyring": "/etc/ceph/ceph.client.radosgw.gateway.keyring",
      "rgw socket path": "''",
      "rgw frontends": "fastcgi socket_port=9000 socket_host=127.0.0.1",
      "log file": "/var/log/ceph/client.radosgw.gateway.log",
      "rgw print continue": "false",
    }
  notify: restart radosgw

- name: set up /etc/ceph/ceph.conf for radosgw-keystone
  ini_file: dest=/etc/ceph/ceph.conf
    section=client.radosgw.gateway
    option="{{ item.key }}"
    value="{{ item.value }}"
    state="{{ radosgw_keystone | ternary('present', 'absent') }}"
  with_dict:
    { "rgw keystone url": "{{ keystone_proto }}://{{ ip.mgmt }}:5000",
      "rgw keystone accepted roles": "{{ rgw_keystone_accepted_roles }}",
      "rgw keystone token cache size": 500,
      "rgw keystone revocation interval": 500,
      "rgw keystone verify ssl": "false",
      "rgw s3 auth use keystone": "true",
      "rgw keystone admin user": "{{ radosgw_admin_user }}",
      "rgw keystone admin password": "{{ radosgw_admin_password }}",
      "rgw keystone admin project": "{{ radosgw_project_name }}",
      "rgw keystone admin domain": "{{ radosgw_domain_name }}",
      "rgw keystone api version": 3,
      "rgw keystone implicit tenants": "{{ rgw_keystone_implicit_tenants }}",
      "nss db path": "/var/lib/ceph/nss"
    }
  notify: restart radosgw

- name: remove keystone admin token from /etc/ceph/ceph.conf
  ini_file: dest=/etc/ceph/ceph.conf
    section=client.radosgw.gateway
    option="rgw keystone admin token"
    state="absent"
  notify: restart radosgw

- name: make sure /var/lib/ceph/nss exists
  file: path=/var/lib/ceph/nss state=directory mode=0644 owner=root group=root
  when: radosgw_keystone

- name: convert keystone CA cert for radosgw use
  shell: 'openssl x509 -in /etc/keystone/ssl/certs/ca.pem -pubkey | certutil -d /var/lib/ceph/nss -A -n ca -t "TCu,Cu,Tuw"'
  when: radosgw_keystone

- name: convert keystone signing cert for radosgw use
  shell: 'openssl x509 -in /etc/keystone/ssl/certs/signing_cert.pem -pubkey | certutil -A -d /var/lib/ceph/nss -n signing_cert -t "P,P,P"'
  when: radosgw_keystone

- meta: flush_handlers

- name: make sure services are started
  service: name={{ item }} state=started
  with_items:
    - radosgw
