---

- name: install radosgw
  apt: name=radosgw

- name: ensure /etc/systemd/system/ceph-radosgw@.service.d exists
  file: dest=/etc/systemd/system/ceph-radosgw@.service.d state=directory owner=root group=root mode=0755

- name: install 10-name.conf override
  copy: content='[Service]\nEnvironment=CLUSTER={{ ceph_cluster_name }}\n'
        dest=/etc/systemd/system/ceph-radosgw@.service.d/10-name.conf
        owner=root group=root mode=0644
  notify: reload systemd

# Since no existing directory allows access to both ceph and apache, create one
- name: make sure /var/lib/radosgw exists
  file: path=/var/lib/radosgw owner=ceph group=ceph mode=0755 state=directory

- name: set up ceph.conf for radosgw
  ini_file: dest=/etc/ceph/{{ ceph_cluster_name }}.conf
    section=client.{{ radosgw_instance }}
    option="{{ item.key }}"
    value="{{ item.value }}"
  with_dict:
    { "host" : "{{ inventory_hostname }}",
      "keyring": "/etc/ceph/{{ ceph_cluster_name }}.client.{{ radosgw_instance }}.keyring",
      "rgw frontends": "civetweb port=127.0.0.1:{{ radosgw_port }}",
      "log file": "/var/log/ceph/client.{{ radosgw_instance }}.log",
      "rgw print continue": "false",
    }
  notify: restart radosgw

- name: set up ceph.conf for radosgw-keystone
  ini_file: dest=/etc/ceph/{{ ceph_cluster_name }}.conf
    section=client.{{ radosgw_instance }}
    option="{{ item.key }}"
    value="{{ item.value }}"
    state="{{ radosgw_keystone | ternary('present', 'absent') }}"
  with_dict:
    { "rgw keystone url": "{{ keystone_proto }}://{{ ip.mgmt }}:5000",
      "rgw keystone accepted roles": "{{ radosgw_keystone_accepted_roles }}",
      "rgw keystone token cache size": 500,
      "rgw keystone revocation interval": 500,
      "rgw keystone verify ssl": "false",
      "rgw s3 auth use keystone": "true",
      "rgw keystone admin user": "{{ radosgw_admin_user }}",
      "rgw keystone admin password": "{{ radosgw_admin_password }}",
      "rgw keystone admin project": "{{ radosgw_project_name }}",
      "rgw keystone admin domain": "{{ radosgw_domain_name }}",
      "rgw keystone api version": 3,
      "rgw keystone implicit tenants": "{{ radosgw_keystone_implicit_tenants }}"
    }
  notify: restart radosgw

- name: remove keystone admin token from ceph.conf
  ini_file: dest=/etc/ceph/{{ ceph_cluster_name }}.conf
    section=client.{{ radosgw_instance }}
    option="rgw keystone admin token"
    state="absent"
  notify: restart radosgw

- meta: flush_handlers

- name: make sure radosgw is started and enabled at boot
  service: name=ceph-radosgw@{{ radosgw_instance }} state=started enabled=yes
