---

- name: Install mongodb packages
  apt:
    name:
    - mongodb
    - python3-pymongo

- name: deploy mongodb configuration
  template: src=mongodb.conf.j2 dest=/etc/mongodb.conf owner=mongodb group=root mode=0460
  notify: restart mongodb

- name: deploy mongodb keyfile
  copy: content='{{ mongodb_key }}' dest=/etc/mongodb.key owner=mongodb group=root mode=0400
  notify: restart mongodb

- meta: flush_handlers

- name: ensure mongodb is started
  service: name=mongodb state=started enabled=yes

- name: wait for mongodb up
  wait_for: port=27017

- name: query the replica set status
  command: mongo --quiet --eval 'rs.status().info;' admin
  changed_when: False
  register: mongo_status

- set_fact: mongo_initialized=False

- name: determine if the replica set is already initialized
  set_fact: mongo_initialized=True
  when: hostvars[item].mongo_status.stdout.find('run rs.initiate') == -1
  with_items: "{{ groups['mongodb'] }}"
  run_once: True

- name: initialize replica set
  command: mongo --quiet --eval '{{ lookup('template','../templates/mongo_init.js.j2') }}' admin
  when: mongo_initialized == False
  run_once: True

- name: wait until the replica set is initialized
  command: mongo --quiet --eval 'rs.status().myState;' admin
  register: mongo_status
  run_once: True
  when: mongo_initialized == False
  until: mongo_status.stdout == '1'
  retries: 10
  delay: 5

- name: determine the master node
  command: mongo --quiet --eval 'rs.isMaster().ismaster' admin
  changed_when: False
  register: mongo_master

- name: ensure the admin user exists
  mongodb_user: login_database=admin database=admin name=admin password={{ mongodb_admin_password }} roles="userAdminAnyDatabase"
  when: mongo_master.stdout == 'true'
  register: mongo_admin
  failed_when: mongo_admin is failed and
      "not authorized" not in mongo_admin.msg and
      "no users authenticated" not in mongo_admin.msg

- name: ensure the cluster admin user exists
  mongodb_user: login_database=admin database=admin login_user=admin login_password={{ mongodb_admin_password }}
    name=clusteradmin password={{ mongodb_clusteradmin_password }} roles="readAnyDatabase,clusterAdmin,clusterManager"
  when: mongo_master.stdout == 'true'

# Cluster expansion
- name: add missing members to the replica set
  command: mongo -u clusteradmin -p {{ mongodb_clusteradmin_password }} --quiet --eval 'rs.add("{{ item }}").ok' admin
  when: mongo_master.stdout == 'true'
  register: mongo_result
  changed_when: mongo_result.stdout == '1'
  with_items: "{{ groups['mongodb'] }}"

- name: wait until the replica set is initialized
  command: mongo -u clusteradmin -p {{ mongodb_clusteradmin_password }} --quiet --eval 'rs.status().myState;' admin
  register: mongo_status
  until: mongo_status.stdout == '1' or mongo_status.stdout == '2'
  changed_when: False
  retries: 10
  delay: 5
