---

cinder_db_user: cinder
cinder_mysql_server: "{{ vip_mgmt }}"
cinder_db: cinder
cinder_rabbit_user: cinder
cinder_domain_id: "{{ keystone_domain_id }}"

cinder_volume_backend: lvm
cinder_volume_rbd_user: volume
cinder_volume_rbd_pool: volume
cinder_backup_rbd_pool: backup
cinder_backup_rbd_user: backup