---

cinder_db_user: cinder
cinder_mysql_server: "{{ vip_mgmt }}"
cinder_db: cinder
cinder_rabbit_user: cinder
cinder_domain_name: "{{ keystone_domain_name }}"

cinder_backend: lvm
cinder_ceph_pool: volumes
cinder_ceph_user: cinder
cinder_backup_ceph_pool: backups
cinder_backup_ceph_user: cinder-backup
