---

cinder_db_user: cinder
cinder_mysql_server: "{{ vip_mgmt }}"
cinder_db: cinder
cinder_rabbit_user: cinder
cinder_admin_user: cinder
cinder_domain_name: "{{ keystone_domain_name }}"
cinder_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
cinder_project_name: "{{ keystone_service_project_name | default('service') }}"

cinder_backend: lvm
cinder_ceph_pool: volumes
cinder_ceph_user: cinder
cinder_backup_ceph_pool: backups
cinder_backup_ceph_user: cinder-backup

cinder_syslog_use: "{{ syslog_use | default(False) }}"

cinder_debug: False

keystone_proto: "{{ (keystone_ssl | default(False)) | ternary('https', 'http') }}"
os_proto: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}"
ssl_insecure: False
SSLCACertificateFileSource:
SSLCACertificateFile: "{{ (SSLCACertificateFileSource is not none and SSLCACertificateFileSource | trim != '') | ternary('/etc/ssl/certs/openstack.ca.crt','') }}"
