- include: ceph.yml

- hosts: ceph_monitor[0]
  become: True
  tasks:
    - name: create pools
      command: ceph --cluster {{ ceph_cluster_name | default('ceph') }} osd pool create {{ item }} 32
      with_items:
        - images
        - volumes
        - backups
        - vms
        - gnocchi

- include: main.yml

- hosts: gnocchi[0]
  become: True
  tasks:
    - name: create gnocchi storage
      command: su gnocchi -s /bin/sh -c '/usr/bin/gnocchi-upgrade'

    - name: create incoming sacks
      command: su gnocchi -s /bin/sh -c '/usr/bin/gnocchi-change-sack-size --sacks 10'
      failed_when: False
