- include: ceph.yml

- hosts: ceph_monitor
  become: True
  tasks:
    - name: create pools
      command: ceph --cluster {{ ceph_cluster_name | default('ceph') }} osd pool create {{ item }} 32
      with_items:
        - images
        - volumes
        - backups
        - vms
        - gnocchi

- include: main.yml
