---

- hosts:
    - ceph_monitor
    - ceph_osd
  become: True
  max_fail_percentage: 0
  roles:
    - apt
  pre_tasks:
    - name: check for Ansible version > 2.0.1
      local_action: assert that="{{ ansible_version.string | version_compare('2.0.1', '>=') }}"
      run_once: True
      become: False

- hosts: ceph_monitor
  become: True
  max_fail_percentage: 0
  serial: 1
  tasks:
    - name: upgrade ceph
      apt: name=ceph state=latest
      notify: restart ceph-monitor
  handlers:
    - name: restart ceph-monitor
      service: name=ceph-mon state=restarted

- hosts: ceph_monitor
  become: True
  max_fail_percentage: 0
  roles:
    - ceph_monitor

- hosts: ceph_osd
  become: True
  max_fail_percentage: 0
  serial: 1
  tasks:
    - name: set osd noout
      command: ceph --cluster {{ ceph_cluster_name | default('ceph') }} osd set noout
      delegate_to: "{{ groups['ceph_monitor'][0] }}"

    - block:

      - name: collect OSDs
        shell: cat /var/lib/ceph/osd/*/whoami
        changed_when: False
        register: ceph_osds

      - name: upgrade ceph
        apt: name=ceph state=latest
        notify: restart OSDs

      - meta: flush_handlers

      - pause:
          prompt: "press a key when the OSDs are back"

#TODO: wait for OSDs are back
      always:
        - name: unset osd noout
          command: ceph --cluster {{ ceph_cluster_name | default('ceph') }} osd unset noout
          delegate_to: "{{ groups['ceph_monitor'][0] }}"

  handlers:
    - name: restart OSDs
      service: name=ceph-osd@{{ item }} state=restarted
      with_items: "{{ ceph_osds.stdout_lines }}"
