---

- hosts: ceph_monitor
  become: True
  max_fail_percentage: 0
  roles:
    - common
    - ceph_monitor

- hosts: ceph_osd
  become: True
  max_fail_percentage: 0
  roles:
    - common
    - ceph_osd
