---

- hosts:
    - ceph_monitor
    - ceph_osd
  become: True
  max_fail_percentage: 0
  roles:
    - apt
  pre_tasks:
    - name: check for Ansible version > 2.0.1
      local_action: assert that="{{ ansible_version.string | version_compare('2.0.1', '>=') }}"
      run_once: True
      become: False

- hosts: ceph_monitor
  become: True
  max_fail_percentage: 0
  serial: 1
  tasks:
    - name: upgrade ceph
      apt: name=ceph state=latest
      notify: restart ceph-monitor

    - name: fix monitor owner
      file: dest=/var/lib/ceph/mon/{{ ceph_cluster_name | default('ceph')}}-{{ inventory_hostname }}
          owner=ceph group=root recurse=yes

    - meta: flush_handlers

    - name: ensure ceph monitor is started
      service: name=ceph-mon state=started enabled=yes

  handlers:
    - name: restart ceph-monitor
      service: name=ceph-mon state=restarted

- hosts: ceph_osd
  become: True
  max_fail_percentage: 0
  serial: 1
  tasks:
    - name: set osd noout
      command: ceph --cluster {{ ceph_cluster_name | default('ceph') }} osd set noout
      delegate_to: "{{ groups['ceph_monitor'][0] }}"

    - block:

      - name: collect OSDs
        shell: cat /var/lib/ceph/osd/*/whoami
        changed_when: False
        register: ceph_osds

      - name: upgrade ceph
        apt: name=ceph state=latest

      - name: ensure ceph OSDs are stopped
        service: name=ceph-osd@{{ item }} state=stopped
        with_items: "{{ ceph_osds.stdout_lines }}"

      - name: fix OSD owner
        file: dest=/var/lib/ceph/osd
            owner=ceph group=root recurse=yes follow=yes

      - name: ensure ceph OSDs are started
        service: name=ceph-osd@{{ item }} state=started enabled=yes
        with_items: "{{ ceph_osds.stdout_lines }}"

#TODO: wait for OSDs are back
      always:
        - name: unset osd noout
          command: ceph --cluster {{ ceph_cluster_name | default('ceph') }} osd unset noout
          delegate_to: "{{ groups['ceph_monitor'][0] }}"
