---

- hosts:
    - ceph_monitor
    - ceph_osd
  become: True
  max_fail_percentage: 0
  roles:
    - common
  pre_tasks:
    - name: check for Ansible version > 2.0.1
      local_action: assert that="{{ ansible_version.string | version_compare('2.0.1', '>=') }}"
      run_once: True
      become: False

- hosts: ceph_monitor
  become: True
  max_fail_percentage: 0
  serial: 1
  tasks:
    - name: upgrade ceph
      apt: name=ceph state=latest
      notify: restart ceph-monitor

    - name: fix monitor owner
      file: dest=/var/lib/ceph/mon/{{ ceph_cluster_name | default('ceph')}}-{{ inventory_hostname }}
          owner=ceph group=root recurse=yes

    - meta: flush_handlers

    - name: ensure ceph monitor is started
      service: name=ceph-mon state=started enabled=yes args="id={{ inventory_hostname }}"

  handlers:
    - name: restart ceph-monitor
      service: name=ceph-mon state=restarted args="id={{ inventory_hostname }}"

- hosts: ceph_osd
  become: True
  max_fail_percentage: 0
  serial: 1
  tasks:
    - name: set osd noout
      command: ceph osd set noout
      delegate_to: "{{ groups['ceph_monitor'][0] }}"

    - block:
      - name: upgrade ceph
        apt: name=ceph state=latest

      - name: ensure ceph OSDs are stopped
        service: name=ceph-osd-all state=stopped

      - name: fix OSD owner
        file: dest=/var/lib/ceph/osd
            owner=ceph group=root recurse=yes follow=yes

      - name: ensure ceph OSDs are started
        service: name=ceph-osd-all state=started enabled=yes

      always:
        - name: unset osd noout
          command: ceph osd unset noout
          delegate_to: "{{ groups['ceph_monitor'][0] }}"
