---

- hosts: localhost
  become: False
  gather_facts: False
  tasks:

    - name: check undefined secrets
      local_action: 'shell
        for secret in $(grep -o "^[a-z_].*:" "{{ playbook_dir }}/scripts/secrets.yml.template"); do
        grep -q "^$secret" "{{ playbook_dir }}/group_vars/all/secrets.yml" || echo "$secret";
        done'
      changed_when: False
      register: missing_secrets

    - name: display missing secrets
      fail:
        msg: "Undefined secrets: {{ missing_secrets.stdout_lines }} Forgot to run scripts/generate_secrets.py?"
      when: missing_secrets.stdout_lines | count > 0
