---

- hosts: galera
  become: True
  max_fail_percentage: 0
  roles:
    - common
  pre_tasks:
    - name: check for Ansible version > 2.0.1
      local_action: assert that="{{ ansible_version.string | version_compare('2.0.1', '>=') }}"
      run_once: True
      become: False

- hosts: galera
  become: True
  max_fail_percentage: 0
  serial: 1
  tasks:

    - block:

      - name: remove current host from haproxy
        haproxy: host={{ inventory_hostname }} backend=galera-back socket=/run/haproxy/admin.sock state=disabled wait=yes
        delegate_to: "{{ item }}"
        with_items: "{{ groups['haproxy'] }}"

      - name: unmanage galera
        command: crm resource unmanage p_galera

      - name: upgrade packages
        apt: name={{ item }} state=latest
        with_items:
          - percona-xtrabackup
          - percona-xtradb-cluster-server-5.6
          - percona-xtradb-cluster-galera-3

      always:

        - name: manage galera
          command: crm resource manage p_galera

        - name: readd current host to haproxy
          haproxy: host={{ inventory_hostname }} backend=galera-back socket=/run/haproxy/admin.sock state=enabled wait=yes
          delegate_to: "{{ item }}"
          with_items: "{{ groups['haproxy'] }}"
