---

- hosts: galera
  user: ansible
  sudo: True
  max_fail_percentage: 0
  roles:
    - common
    - galera
  vars:
    apt_extra_repos:
      - { name: "percona", repo: "http://repo.percona.com/apt trusty main" }
    apt_extra_keys:
      - { keyserver: "keys.gnupg.net", keyid: "1C4CBDCDCD2EFD2A" }

- hosts: haproxy
  user: ansible
  sudo: True
  max_fail_percentage: 0
  roles:
    - haproxy_service
  vars:
    haproxy_services:
      - haproxy_service_name: galera
        haproxy_bind_hosts:
          - "{{ vip_mgmt }}"
        haproxy_backend_nodes: "{{ [groups['galera'][0]] }}"
        haproxy_backup_nodes: "{{ groups['galera'][1:] }}"
        haproxy_port: 3306
        haproxy_check_port: 9200
        haproxy_balance_type: tcp
        haproxy_timeout_client: 5000s
        haproxy_timeout_server: 5000s
        haproxy_backend_options:
          - httpchk