---

- hosts: galera
  become: True
  max_fail_percentage: 0
  roles:
    - role: apt
      apt_extra_repos:
        - { name: "percona", repo: "http://repo.percona.com/apt {{ ansible_distribution_release }} main" }
      apt_extra_keys:
        - { keyserver: "keyserver.ubuntu.com", keyid: "1C4CBDCDCD2EFD2A" }
        - { keyserver: "keyserver.ubuntu.com", keyid: "9334A25F8507EFA5" }

    - galera

- hosts: haproxy
  become: True
  max_fail_percentage: 0
  roles:
    - role: haproxy_service
      haproxy_services:
        - haproxy_service_name: galera
          haproxy_bind_hosts:
            - "{{ vip_mgmt }}"
          haproxy_backend_nodes: "{{ [groups['galera'][0]] }}"
          haproxy_backup_nodes: "{{ groups['galera'][1:] }}"
          haproxy_port: 3306
          haproxy_check_port: 9200
          haproxy_balance_type: tcp
          haproxy_balance_alg: roundrobin
          haproxy_timeout_client: 5000s
          haproxy_timeout_server: 5000s
          haproxy_backend_options:
            - httpchk
