---

- hosts: aodh[0]
  max_fail_percentage: 0
  roles:
    - role: os_keystone_service
      keystone_service_name: aodh
      keystone_service_type: alarming
      keystone_service_description: "OpenStack Alarming Service"
      keystone_public_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_public_address }}:8042"
      keystone_internal_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_internal_address }}:8042"
      keystone_admin_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_admin_address }}:8042"
      keystone_region: "{{ keystone_region_name }}"
      keystone_users:
        - keystone_user: "{{ aodh_admin_user | default('aodh') }}"
          keystone_domain_name: "{{ aodh_domain_name | default(keystone_domain_name) }}"
          keystone_password: "{{ aodh_admin_password }}"
          keystone_project_name: "{{ keystone_service_project_name | default('service') }}"
          keystone_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
          keystone_role:
            - admin
            - service

- hosts: aodh
  become: True
  max_fail_percentage: 0
  roles:
    - apt

    - os_aodh

    - role: apache_frontend
      apache_service_name: aodh
      apache_service_ssl: "{{ os_ssl | default(False) }}"
      apache_services:
        - { port: 8042, wsgi_process: "aodh-api", wsgi_user: "aodh", wsgi_group: "aodh", wsgi_script: "/var/www/cgi-bin/aodh/aodh-api" }

- hosts: haproxy
  become: True
  max_fail_percentage: 0
  roles:
    - role: haproxy_service
      haproxy_services:
        - haproxy_service_name: aodh_api
          haproxy_backend_nodes: "{{ groups['aodh'] }}"
          haproxy_bind_hosts:
            - "{{ vip_mgmt }}"
            - "{{ vip_public }}"
          haproxy_port: 8042
          haproxy_balance_type: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}"
          haproxy_backend_options: "{{ (os_ssl | default(False)) | ternary(['httpchk /healthcheck'], ['forwardfor', 'httpchk /healthcheck', 'httplog']) }}"
