---

- hosts: barbican[0]
  max_fail_percentage: 0
  roles:
    - role: os_keystone_service
      keystone_service_name: barbican
      keystone_service_type: key-manager
      keystone_service_description: "OpenStack Barbican Service"
      keystone_public_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_public_address }}:9311"
      keystone_internal_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_internal_address }}:9311"
      keystone_admin_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_admin_address }}:9311"
      keystone_region: "{{ keystone_region_name }}"
      keystone_users:
        - keystone_user: "{{ barbican_admin_user | default('barbican') }}"
          keystone_domain_name: "{{ barbican_domain_name | default(keystone_domain_name) }}"
          keystone_password: "{{ barbican_admin_password }}"
          keystone_project_name: "{{ keystone_service_project_name | default('service') }}"
          keystone_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
          keystone_role:
            - admin
            - service
      keystone_roles:
        - key-manager:service-admin
        - creator
        - observer
        - audit

- hosts: barbican
  become: True
  max_fail_percentage: 0
  roles:
    - apt

    - os_barbican

    - role: apache_frontend
      apache_service_name: barbican
      apache_service_ssl: "{{ os_ssl | default(False) }}"
      apache_services:
        - { port: 9311, wsgi_process: "barbican-api", wsgi_user: "barbican", wsgi_group: "barbican", wsgi_script: "/var/www/cgi-bin/barbican/barbican-api" }

- hosts: haproxy
  become: True
  max_fail_percentage: 0
  roles:
    - role: haproxy_service
      haproxy_services:
        - haproxy_service_name: barbican_api
          haproxy_backend_nodes: "{{ groups['barbican'] }}"
          haproxy_bind_hosts:
            - "{{ vip_mgmt }}"
            - "{{ vip_public }}"
          haproxy_port: 9311
          haproxy_balance_type: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}"
          haproxy_backend_options: "{{ (os_ssl | default(False)) | ternary(['httpchk'], ['forwardfor', 'httpchk', 'httplog']) }}"
