---

- hosts: cinder[0]
  user: ansible
  max_fail_percentage: 0
  roles:
    - os_keystone_service
  vars:
    keystone_service_name: cinder
    keystone_service_type: volume
    keystone_service_description: "OpenStack Block Storage Service"
    keystone_public_url: "http://{{ keystone_internal_ip }}:8776/v1/%(tenant_id)s"
    keystone_internal_url: "http://{{ keystone_internal_ip }}:8776/v1/%(tenant_id)s"
    keystone_admin_url: "http://{{ keystone_public_ip }}:8776/v1/%(tenant_id)s"
    keystone_region: "{{ keystone_region_name }}"
    keystone_projects:
      - keystone_project_name: service
        keystone_project_description: "Service Project"
        keystone_user: cinder
        keystone_domain: "{{ keystone_domain_id }}"
        keystone_password: "{{ cinder_admin_password }}"
        keystone_role: admin

- hosts: cinder[0]
  user: ansible
  max_fail_percentage: 0
  roles:
    - os_keystone_service
  vars:
    keystone_service_name: cinderv2
    keystone_service_type: volumev2
    keystone_service_description: "OpenStack Block Storage Service"
    keystone_public_url: "http://{{ keystone_internal_ip }}:8776/v2/%(tenant_id)s"
    keystone_internal_url: "http://{{ keystone_internal_ip }}:8776/v2/%(tenant_id)s"
    keystone_admin_url: "http://{{ keystone_public_ip }}:8776/v2/%(tenant_id)s"
    keystone_region: "{{ keystone_region_name }}"
    keystone_projects:
      - keystone_project_name: service
        keystone_project_description: "Service Project"
        keystone_user: cinder
        keystone_domain: "{{ keystone_domain_id }}"
        keystone_password: "{{ cinder_admin_password }}"
        keystone_role: admin

- hosts:
    - cinder
    - cinder_volume
  user: ansible
  sudo: True
  max_fail_percentage: 0
  roles:
    - common
    - os_cinder

- hosts: cinder
  user: ansible
  sudo: True
  max_fail_percentage: 0
  roles:
    - { role: ceph_client, when: cinder_backend == 'ceph' }
  vars:
    ceph_user: "{{ cinder_ceph_user }}"
    ceph_rights: "mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=volumes, allow rwx pool=vms, allow rx pool={{ cinder_ceph_pool }}'"
    ceph_keyring_owner: cinder

- hosts: cinder
  user: ansible
  sudo: True
  max_fail_percentage: 0
  roles:
    - { role: ceph_client, when: cinder_backend == 'ceph' }
  vars:
    ceph_user: "{{ cinder_backup_ceph_user }}"
    ceph_rights: "mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool={{ cinder_backup_ceph_pool }}'"
    ceph_keyring_owner: cinder

- hosts: haproxy
  user: ansible
  sudo: True
  max_fail_percentage: 0
  roles:
    - haproxy_service
  vars:
    haproxy_services:
      - haproxy_service_name: cinder_api
        haproxy_backend_nodes: "{{ groups['cinder'] }}"
        haproxy_bind_hosts:
          - "{{ vip_mgmt }}"
          - "{{ vip_public }}"
        haproxy_port: 8776
        haproxy_balance_type: http
        haproxy_backend_options:
          - forwardfor
          - httpchk
          - httplog
