---

- hosts: cinder[0]
  max_fail_percentage: 0
  roles:
    - os_keystone_service
  vars:
    keystone_service_name: cinder
    keystone_service_type: volume
    keystone_service_description: "OpenStack Block Storage Service"
    keystone_public_url: "http://{{ vip_public }}:8776/v1/%(tenant_id)s"
    keystone_internal_url: "http://{{ vip_mgmt }}:8776/v1/%(tenant_id)s"
    keystone_admin_url: "http://{{ vip_mgmt }}:8776/v1/%(tenant_id)s"
    keystone_region: "{{ keystone_region_name }}"
    keystone_users:
      - keystone_user: "{{ cinder_admin_user | default('cinder') }}"
        keystone_domain_name: "{{ cinder_domain_name | default(keystone_domain_name) }}"
        keystone_password: "{{ cinder_admin_password }}"
        keystone_project_name: "{{ keystone_service_project_name | default('service') }}"
        keystone_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
        keystone_role: admin

- hosts: cinder[0]
  max_fail_percentage: 0
  roles:
    - os_keystone_service
  vars:
    keystone_service_name: cinderv2
    keystone_service_type: volumev2
    keystone_service_description: "OpenStack Block Storage Service"
    keystone_public_url: "http://{{ vip_public }}:8776/v2/%(tenant_id)s"
    keystone_internal_url: "http://{{ vip_mgmt }}:8776/v2/%(tenant_id)s"
    keystone_admin_url: "http://{{ vip_mgmt }}:8776/v2/%(tenant_id)s"
    keystone_region: "{{ keystone_region_name }}"

- hosts:
    - cinder
    - cinder_volume
  sudo: True
  max_fail_percentage: 0
  roles:
    - common
    - os_cinder

- hosts: cinder
  sudo: True
  max_fail_percentage: 0
  roles:
    - apache_frontend
  vars:
    service_name: cinder
    service_ports:
      - 8776

- hosts: cinder
  sudo: True
  max_fail_percentage: 0
  roles:
    - { role: ceph_client, when: cinder_backend == 'ceph' }
  vars:
    ceph_user: "{{ cinder_ceph_user }}"
    ceph_rights: "mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool={{ cinder_ceph_pool }}, allow rwx pool={{ nova_ephemeral_ceph_pool }}, allow rx pool={{ glance_ceph_pool }}'"
    ceph_keyring_owner: cinder

- hosts: cinder
  sudo: True
  max_fail_percentage: 0
  roles:
    - { role: ceph_client, when: cinder_backend == 'ceph' }
  vars:
    ceph_user: "{{ cinder_backup_ceph_user }}"
    ceph_rights: "mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool={{ cinder_backup_ceph_pool }}'"
    ceph_keyring_owner: cinder

- hosts: haproxy
  sudo: True
  max_fail_percentage: 0
  roles:
    - haproxy_service
  vars:
    haproxy_services:
      - haproxy_service_name: cinder_api
        haproxy_backend_nodes: "{{ groups['cinder'] }}"
        haproxy_bind_hosts:
          - "{{ vip_mgmt }}"
          - "{{ vip_public }}"
        haproxy_port: 8776
        haproxy_balance_type: http
        haproxy_backend_options:
          - forwardfor
          - httpchk
          - httplog
