---

- hosts: ceilometer_controller[0]
  max_fail_percentage: 0
  roles:
    - role: os_keystone_service
      keystone_users:
        - keystone_user: "{{ ceilometer_admin_user | default('ceilometer') }}"
          keystone_domain_name: "{{ ceilometer_domain_name | default(keystone_domain_name) }}"
          keystone_password: "{{ ceilometer_admin_password }}"
          keystone_project_name: "{{ keystone_service_project_name | default('service') }}"
          keystone_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
          keystone_role:
            - admin
            - service
            - ResellerAdmin

- hosts:
    - ceilometer_controller
    - ceilometer_compute
  become: True
  max_fail_percentage: 0
  roles:
    - apt
    - os_ceilometer
