---

- hosts:
    - keystone
    - swift_proxy
    - swift_storage
    - glance
    - horizon
    - nova_controller
    - neutron_controller
    - neutron_l3
    - gnocchi
    - ceilometer_controller
    - aodh
    - heat
    - trove
    - cinder
    - murano
    - sahara
    - barbican
    - ironic
    - designate
    - magnum
    - manila
    - mistral
    - senlin
    - ceph_radosgw
  become: True
  max_fail_percentage: 0
  roles:
    - apt
  pre_tasks:
    - name: check for Ansible version > 2.0.1
      local_action: assert that="{{ ansible_version.string is version_compare('2.0.1', '>=') }}"
      run_once: True
      become: False
  tasks:
    - name: make sure aptitude is installed
      apt: name=aptitude


# Mask apache configs from the packages

- hosts: barbican
  become: True
  max_fail_percentage: 0
  tasks:
    - name: mask barbican-api apache config
      copy: content='' dest=/etc/apache2/conf-available/barbican-api.conf owner=root group=root mode=0644

- hosts: aodh
  become: True
  max_fail_percentage: 0
  tasks:
    - name: mask aodh-api apache config
      copy: content='' dest=/etc/apache2/sites-available/aodh-api.conf owner=root group=root mode=0644

- hosts: ceilometer_controller
  become: True
  max_fail_percentage: 0
  tasks:
    - name: mask ceilometer-api apache config
      copy: content='' dest=/etc/apache2/sites-available/ceilometer-api.conf owner=root group=root mode=0644

- hosts: cinder
  become: True
  max_fail_percentage: 0
  tasks:
    - name: mask cinder-wsgi apache config
      copy: content='' dest=/etc/apache2/conf-available/cinder-wsgi.conf owner=root group=root mode=0644

- hosts: gnocchi
  become: True
  max_fail_percentage: 0
  tasks:
    - name: mask gnocchi-api apache config
      copy: content='' dest=/etc/apache2/sites-available/gnocchi-api.conf owner=root group=root mode=0644


# Upgrade keystone all at once, since it is not supporting rolling upgrades yet

- hosts: keystone
  become: True
  max_fail_percentage: 0
  tasks:
    - name: mask keystone apache config
      copy: content='' dest=/etc/apache2/sites-available/keystone.conf owner=root group=root mode=0644

    - name: upgrade keystone
      apt: name={{ item }} state=latest
      with_items:
        - keystone
        - python-keystoneclient
        - python-oslo.log
        - python-oslo.policy
        - python-webob

- hosts: memcached
  become: True
  max_fail_percentage: 0
  tasks:
    - name: restart memcached
      service: name=memcached state=restarted

- hosts: keystone
  become: True
  max_fail_percentage: 0
  tasks:
    - name: reload apache2
      service: name=apache2 state=reloaded

    - name: run keystone playbook
      local_action: command ansible-playbook {{ playbook_dir }}/os_keystone.yml -i "{{ inventory_file }}"
      become: False
      run_once: True


# Neutron server upgrade

- hosts:
    - neutron_controller
  become: True
  max_fail_percentage: 0
  tasks:
    - name: upgrade neutron server
      apt: name={{ item }} state=latest
      with_items:
        - neutron-server
        - python-neutron
        - python-neutron-fwaas
        - python-neutron-lbaas
        - python-neutron-vpnaas
        - python-pecan
      notify: restart neutron-server

    - name: run neutron playbook
      local_action: command ansible-playbook {{ playbook_dir }}/os_neutron.yml -i "{{ inventory_file }}" -l "{{ ','.join(groups['neutron_controller']) }}"
      become: False
      run_once: True

  handlers:
    - name: restart neutron-server
      service: name=neutron-server state=restarted


# Upgrade first host(s)

- hosts:
    - swift_proxy[0]
    - glance[0]
    - horizon[0]
    - nova_controller[0]
    - neutron_l3[0]
    - gnocchi[0]
    - ceilometer_controller[0]
    - aodh[0]
    - heat[0]
    - trove[0]
    - cinder[0]
    - murano[0]
    - sahara[0]
    - barbican[0]
    - ironic[0]
    - designate[0]
    - magnum[0]
    - manila[0]
    - mistral[0]
    - senlin[0]
    - ceph_radosgw[0]
  become: True
  max_fail_percentage: 0
  serial: 1
  tasks:

    - block:

      - name: remove current host from haproxy
        haproxy: host={{ inventory_hostname }} socket=/run/haproxy/admin.sock state=disabled
        delegate_to: "{{ item }}"
        with_items: "{{ groups['haproxy'] }}"

      - name: upgrade packages
        apt: upgrade=yes

      - name: run playbooks on the first hosts
        local_action: command ansible-playbook {{ playbook_dir }}/{{ item.playbook }} -i "{{ inventory_file }}" -l "{{ inventory_hostname }}"
        when: inventory_hostname in item.group
        with_items:
          - { playbook: "os_glance.yml", group: "{{ groups['glance'] }}" }
          - { playbook: "os_neutron.yml", group: "{{ groups['neutron_l3'] }}" }
          - { playbook: "os_nova.yml", group: "{{ groups['nova_controller'] }}" }
          - { playbook: "os_gnocchi.yml", group: "{{ groups['gnocchi'] }}" }
          - { playbook: "os_ceilometer.yml", group: "{{ groups['ceilometer_controller'] }}" }
          - { playbook: "os_aodh.yml", group: "{{ groups['aodh'] }}" }
          - { playbook: "os_heat.yml", group: "{{ groups['heat'] }}" }
          - { playbook: "os_cinder.yml", group: "{{ groups['cinder'] }}" }
          - { playbook: "os_trove.yml", group: "{{ groups['trove'] }}" }
          - { playbook: "os_horizon.yml", group: "{{ groups['horizon'] }}" }
          - { playbook: "os_barbican.yml", group: "{{ groups['barbican'] }}" }
          - { playbook: "os_murano.yml", group: "{{ groups['murano'] }}" }
          - { playbook: "os_sahara.yml", group: "{{ groups['sahara'] }}" }
          - { playbook: "os_designate.yml", group: "{{ groups['designate'] }}" }
          - { playbook: "os_magnum.yml", group: "{{ groups['magnum'] }}" }
          - { playbook: "os_manila.yml", group: "{{ groups['manila'] }}" }
          - { playbook: "os_mistral.yml", group: "{{ groups['mistral'] }}" }
          - { playbook: "os_senlin.yml", group: "{{ groups['senlin'] }}" }
          - { playbook: "ceph_radosgw.yml", group: "{{ groups['ceph_radosgw'] }}" }
        become: False

      always:

        - name: readd current host to haproxy
          haproxy: host={{ inventory_hostname }} socket=/run/haproxy/admin.sock state=enabled
          delegate_to: "{{ item }}"
          with_items: "{{ groups['haproxy'] }}"


# Upgrade other host(s)

- hosts:
    - swift_proxy[1:]
    - glance[1:]
    - horizon[1:]
    - nova_controller[1:]
    - neutron_l3[1:]
    - gnocchi[1:]
    - ceilometer_controller[1:]
    - aodh[1:]
    - heat[1:]
    - trove[1:]
    - cinder[1:]
    - murano[1:]
    - sahara[1:]
    - barbican[1:]
    - ironic[1:]
    - designate[1:]
    - magnum[1:]
    - manila[1:]
    - mistral[1:]
    - senlin[1:]
    - ceph_radosgw[1:]
  become: True
  max_fail_percentage: 0
  tasks:

    - block:

      - name: remove hosts[1:] from haproxy
        haproxy: host={{ inventory_hostname }} socket=/run/haproxy/admin.sock state=disabled
        delegate_to: "{{ item }}"
        with_items: "{{ groups['haproxy'] }}"

      - name: upgrade packages
        apt: upgrade=yes

      - name: run playbooks on the other hosts
        local_action: command ansible-playbook {{ playbook_dir }}/{{ item.playbook }} -i "{{ inventory_file }}" -l "{{ inventory_hostname }}"
        when: inventory_hostname in item.group
        with_items:
          - { playbook: "os_glance.yml", group: "{{ groups['glance'] }}" }
          - { playbook: "os_neutron.yml", group: "{{ groups['neutron_l3'] }}" }
          - { playbook: "os_nova.yml", group: "{{ groups['nova_controller'] }}" }
          - { playbook: "os_gnocchi.yml", group: "{{ groups['gnocchi'] }}" }
          - { playbook: "os_ceilometer.yml", group: "{{ groups['ceilometer_controller'] }}" }
          - { playbook: "os_aodh.yml", group: "{{ groups['aodh'] }}" }
          - { playbook: "os_heat.yml", group: "{{ groups['heat'] }}" }
          - { playbook: "os_cinder.yml", group: "{{ groups['cinder'] }}" }
          - { playbook: "os_trove.yml", group: "{{ groups['trove'] }}" }
          - { playbook: "os_horizon.yml", group: "{{ groups['horizon'] }}" }
          - { playbook: "os_barbican.yml", group: "{{ groups['barbican'] }}" }
          - { playbook: "os_murano.yml", group: "{{ groups['murano'] }}" }
          - { playbook: "os_sahara.yml", group: "{{ groups['sahara'] }}" }
          - { playbook: "os_designate.yml", group: "{{ groups['designate'] }}" }
          - { playbook: "os_magnum.yml", group: "{{ groups['magnum'] }}" }
          - { playbook: "os_manila.yml", group: "{{ groups['manila'] }}" }
          - { playbook: "os_mistral.yml", group: "{{ groups['mistral'] }}" }
          - { playbook: "os_senlin.yml", group: "{{ groups['senlin'] }}" }
          - { playbook: "ceph_radosgw.yml", group: "{{ groups['ceph_radosgw'] }}" }
        become: False

      always:

        - name: readd hosts[1:] to haproxy
          haproxy: host={{ inventory_hostname }} socket=/run/haproxy/admin.sock state=enabled
          delegate_to: "{{ item }}"
          with_items: "{{ groups['haproxy'] }}"
