---

- hosts: cloudkitty[0]
  max_fail_percentage: 0
  roles:
    - role: os_keystone_service
      keystone_service_name: cloudkitty
      keystone_service_type: rating
      keystone_service_description: "OpenStack Rating Service"
      keystone_public_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_public_address }}:8889"
      keystone_internal_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_internal_address }}:8889"
      keystone_admin_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_admin_address }}:8889"
      keystone_region: "{{ keystone_region_name }}"
      keystone_users:
        - keystone_user: "{{ cloudkitty_admin_user | default('cloudkitty') }}"
          keystone_domain_name: "{{ cloudkitty_domain_name | default(keystone_domain_name) }}"
          keystone_password: "{{ cloudkitty_admin_password }}"
          keystone_project_name: "{{ keystone_service_project_name | default('service') }}"
          keystone_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
          keystone_role:
            - admin
            - service

- hosts: cloudkitty
  become: True
  max_fail_percentage: 0
  roles:
    - apt

    - os_cloudkitty

    - role: apache_frontend
      apache_service_name: cloudkitty
      apache_service_ssl: "{{ os_ssl | default(False) }}"
      apache_proxyprotocol: "{{ proxyprotocol | default(False) }}"
      apache_services:
        - { port: 8889 }

- hosts: haproxy
  become: True
  max_fail_percentage: 0
  roles:
    - role: haproxy_service
      haproxy_services:
        - haproxy_service_name: cloudkitty_api
          haproxy_backend_nodes: "{{ groups['cloudkitty'] }}"
          haproxy_bind_hosts:
            - "{{ vip_mgmt }}"
            - "{{ vip_public }}"
          haproxy_port: 8889
          haproxy_balance_type: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}"
          haproxy_backend_options: "{{ (os_ssl | default(False)) | ternary(['httpchk'], ['forwardfor', 'httpchk', 'httplog']) }}"
          haproxy_proxyprotocol: "{{ proxyprotocol | default(False) }}"
