---

- hosts: designate[0]
  max_fail_percentage: 0
  roles:
    - role: os_keystone_service
      keystone_service_name: designate
      keystone_service_type: dns
      keystone_service_description: "OpenStack DNS Service"
      keystone_public_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_public_address }}:9001"
      keystone_internal_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_internal_address }}:9001"
      keystone_admin_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_admin_address }}:9001"
      keystone_region: "{{ keystone_region_name }}"
      keystone_users:
        - keystone_user: "{{ designate_admin_user | default('designate') }}"
          keystone_domain_name: "{{ designate_domain_name | default(keystone_domain_name) }}"
          keystone_password: "{{ designate_admin_password }}"
          keystone_project_name: "{{ keystone_service_project_name | default('service') }}"
          keystone_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
          keystone_role:
            - admin
            - service

- hosts: designate
  become: True
  max_fail_percentage: 0
  roles:
    - apt

    - os_designate

    - role: apache_frontend
      apache_service_name: designate
      apache_service_ssl: "{{ os_ssl | default(False) }}"
      apache_services:
        - { port: 9001 }

- hosts: haproxy
  become: True
  max_fail_percentage: 0
  roles:
    - role: haproxy_service
      haproxy_services:
        - haproxy_service_name: designate_api
          haproxy_backend_nodes: "{{ groups['designate'] }}"
          haproxy_bind_hosts:
            - "{{ vip_mgmt }}"
            - "{{ vip_public }}"
          haproxy_port: 9001
          haproxy_balance_type: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}"
          haproxy_backend_options: "{{ (os_ssl | default(False)) | ternary(['httpchk'], ['forwardfor', 'httpchk', 'httplog']) }}"
