---

- hosts: glance[0]
  max_fail_percentage: 0
  roles:
    - role: os_keystone_service
      keystone_service_name: glance
      keystone_service_type: image
      keystone_service_description: "OpenStack Image Service"
      keystone_public_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_public_address }}:9292"
      keystone_internal_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_internal_address }}:9292"
      keystone_admin_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_admin_address }}:9292"
      keystone_region: "{{ keystone_region_name }}"
      keystone_users:
        - keystone_user: "{{ glance_admin_user | default('glance') }}"
          keystone_domain_name: "{{ glance_domain_name | default(keystone_domain_name) }}"
          keystone_password: "{{ glance_admin_password }}"
          keystone_project_name: "{{ keystone_service_project_name | default('service') }}"
          keystone_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
          keystone_role: admin

- hosts: glance
  become: True
  max_fail_percentage: 0
  roles:
    - common

    - os_glance

    - role: apache_frontend
      apache_service_name: glance
      apache_service_ssl: "{{ os_ssl | default(False) }}"
      apache_services:
        - { port: 9292 }
        - { port: 9191 }

    - role: ceph_client
      ceph_user: "{{ glance_ceph_user | default('glance') }}"
      ceph_rights: "mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool={{ glance_ceph_pool | default('images') }}'"
      ceph_key: "{{ glance_ceph_key | default(None) }}"
      ceph_keyring_owner: glance
      when: glance_backend | default('files') == 'ceph'

- hosts: haproxy
  become: True
  max_fail_percentage: 0
  roles:
    - role: haproxy_service
      haproxy_services:
        - haproxy_service_name: glance_api
          haproxy_backend_nodes: "{{ groups['glance'] }}"
          haproxy_bind_hosts:
            - "{{ vip_mgmt }}"
            - "{{ vip_public }}"
          haproxy_port: 9292
          haproxy_balance_type: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}"
          haproxy_backend_options: "{{ (os_ssl | default(False)) | ternary(['httpchk /healthcheck'], ['forwardfor', 'httpchk /healthcheck', 'httplog']) }}"

        - haproxy_service_name: glance_registry
          haproxy_backend_nodes: "{{ groups['glance'] }}"
          haproxy_bind_hosts:
            - "{{ vip_mgmt }}"
            - "{{ vip_public }}"
          haproxy_port: 9191
          haproxy_balance_type: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}"
          haproxy_backend_options:
            - httpchk /healthcheck
