---

- hosts: glance[0]
  user: ansible
  max_fail_percentage: 0
  roles:
    - os_keystone_service
  vars:
    keystone_service_name: glance
    keystone_service_type: image
    keystone_service_description: "OpenStack Image Service"
    keystone_public_url: "http://{{ vip_public }}:9292"
    keystone_internal_url: "http://{{ vip_mgmt }}:9292"
    keystone_admin_url: "http://{{ vip_mgmt }}:9292"
    keystone_region: "{{ keystone_region_name }}"
    keystone_projects:
      - keystone_project_name: service
        keystone_project_description: "Service Project"
        keystone_user: glance
        keystone_domain_name: "{{ keystone_domain_name }}"
        keystone_password: "{{ glance_admin_password }}"
        keystone_role: admin

- hosts: glance
  user: ansible
  sudo: True
  max_fail_percentage: 0
  roles:
    - common
    - os_glance

- hosts: glance
  user: ansible
  sudo: True
  max_fail_percentage: 0
  roles:
    - { role: ceph_client, when: glance_backend == 'ceph' }
  vars:
    ceph_user: "{{ glance_ceph_user }}"
    ceph_rights: "mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool={{ glance_ceph_pool }}'"
    ceph_keyring_owner: glance

- hosts: haproxy
  user: ansible
  sudo: True
  max_fail_percentage: 0
  roles:
    - haproxy_service
  vars:
    haproxy_services:
      - haproxy_service_name: glance_api
        haproxy_backend_nodes: "{{ groups['glance'] }}"
        haproxy_bind_hosts:
          - "{{ vip_mgmt }}"
          - "{{ vip_public }}"
        haproxy_port: 9292
        haproxy_balance_type: http
        haproxy_backend_options:
          - forwardfor
          - httpchk
          - httplog

      - haproxy_service_name: glance_registry
        haproxy_backend_nodes: "{{ groups['glance'] }}"
        haproxy_bind_hosts:
          - "{{ vip_mgmt }}"
          - "{{ vip_public }}"
        haproxy_port: 9191
        haproxy_balance_type: http
