---

- hosts: glance[0]
  max_fail_percentage: 0
  roles:
    - os_keystone_service
  vars:
    keystone_service_name: glance
    keystone_service_type: image
    keystone_service_description: "OpenStack Image Service"
    keystone_public_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_public_address }}:9292"
    keystone_internal_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_internal_address }}:9292"
    keystone_admin_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_admin_address }}:9292"
    keystone_region: "{{ keystone_region_name }}"
    keystone_users:
      - keystone_user: "{{ glance_admin_user | default('glance') }}"
        keystone_domain_name: "{{ glance_domain_name | default(keystone_domain_name) }}"
        keystone_password: "{{ glance_admin_password }}"
        keystone_project_name: "{{ keystone_service_project_name | default('service') }}"
        keystone_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
        keystone_role: admin

- hosts: glance
  become: True
  max_fail_percentage: 0
  roles:
    - common
    - os_glance

- hosts: glance
  become: True
  max_fail_percentage: 0
  roles:
    - apache_frontend
  vars:
    service_name: glance
    service_ssl: "{{ os_ssl | default(False) }}"
    services:
      - { port: 9292 }
      - { port: 9191 }

- hosts: glance
  become: True
  max_fail_percentage: 0
  roles:
    - { role: ceph_client, when: glance_backend == 'ceph' }
  vars:
    ceph_user: "{{ glance_ceph_user }}"
    ceph_rights: "mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool={{ glance_ceph_pool }}'"
    ceph_keyring_owner: glance

- hosts: haproxy
  become: True
  max_fail_percentage: 0
  roles:
    - haproxy_service
  vars:
    haproxy_services:
      - haproxy_service_name: glance_api
        haproxy_backend_nodes: "{{ groups['glance'] }}"
        haproxy_bind_hosts:
          - "{{ vip_mgmt }}"
          - "{{ vip_public }}"
        haproxy_port: 9292
        haproxy_balance_type: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}"
        haproxy_backend_options: "{{ (os_ssl | default(False)) | ternary(['httpchk /healthcheck'], ['forwardfor', 'httpchk /healthcheck', 'httplog']) }}"

      - haproxy_service_name: glance_registry
        haproxy_backend_nodes: "{{ groups['glance'] }}"
        haproxy_bind_hosts:
          - "{{ vip_mgmt }}"
          - "{{ vip_public }}"
        haproxy_port: 9191
        haproxy_balance_type: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}"
        haproxy_backend_options:
          - httpchk /healthcheck
