---

- hosts: horizon
  user: ansible
  sudo: True
  max_fail_percentage: 0
  roles:
    - common
    - os_horizon

- hosts: haproxy
  user: ansible
  sudo: True
  max_fail_percentage: 0
  roles:
    - haproxy_service
  vars:
    haproxy_services:
      - haproxy_service_name: horizon
        haproxy_backend_nodes: "{{ groups['horizon'] }}"
        haproxy_bind_hosts:
          - "{{ vip_mgmt }}"
          - "{{ vip_public }}"
        haproxy_port: 80
        haproxy_balance_type: http
        haproxy_backend_options:
          - forwardfor
          - httpchk
          - httplog
