---

- hosts: keystone
  user: ansible
  sudo: True
  max_fail_percentage: 0
  roles:
    - common
    - os_keystone

- hosts: haproxy
  user: ansible
  sudo: True
  max_fail_percentage: 0
  roles:
    - haproxy_service
  vars:
    haproxy_services:
      - haproxy_service_name: keystone_admin
        haproxy_backend_nodes: "{{ groups['keystone'] }}"
        haproxy_bind_hosts:
          - "{{ vip_mgmt }}"
          - "{{ vip_public }}"
        haproxy_port: 35357
        haproxy_balance_type: http
        haproxy_balance_alg: leastconn
        haproxy_backend_options:
          - forwardfor
          - httpchk
          - httplog
      - haproxy_service_name: keystone_service
        haproxy_backend_nodes: "{{ groups['keystone'] }}"
        haproxy_bind_hosts:
          - "{{ vip_public }}"
        haproxy_port: 5000
        haproxy_balance_type: http
        haproxy_balance_alg: leastconn
        haproxy_backend_options:
          - forwardfor
          - httpchk
          - httplog

- hosts: keystone[0]
  user: ansible
  max_fail_percentage: 0
  roles:
    - os_keystone_service
  vars:
    keystone_service_name: keystone
    keystone_service_type: identity
    keystone_service_description: "OpenStack Identity"
    keystone_public_url: "http://{{ keystone_internal_ip }}:5000/v3"
    keystone_internal_url: "http://{{ keystone_internal_ip }}:5000/v3"
    keystone_admin_url: "http://{{ keystone_public_ip }}:35357/v3"
    keystone_region: "{{ keystone_region_name }}"
    keystone_projects:
      - keystone_project_name: admin
        keystone_project_description: "Admin Project"
        keystone_user: admin
        keystone_password: "{{ keystone_admin_password }}"
        keystone_role: admin
      - keystone_project_name: service
        keystone_project_description: "Service Project"