---

- hosts: keystone
  user: ansible
  sudo: True
  max_fail_percentage: 0
  roles:
    - common
    - os_keystone

- hosts: haproxy
  user: ansible
  sudo: True
  max_fail_percentage: 0
  roles:
    - haproxy_service
  vars:
    haproxy_services:
      - haproxy_service_name: keystone_admin
        haproxy_backend_nodes: "{{ groups['keystone'] }}"
        haproxy_bind_hosts:
          - "{{ vip_mgmt }}"
          - "{{ vip_public }}"
        haproxy_port: 35357
        haproxy_balance_type: http
        haproxy_balance_alg: leastconn
        haproxy_backend_options:
          - forwardfor
          - httpchk
          - httplog
      - haproxy_service_name: keystone_service
        haproxy_backend_nodes: "{{ groups['keystone'] }}"
        haproxy_bind_hosts:
          - "{{ vip_public }}"
        haproxy_port: 5000
        haproxy_balance_type: http
        haproxy_balance_alg: leastconn
        haproxy_backend_options:
          - forwardfor
          - httpchk
          - httplog

#The plays below must run without an installed keystone (e.g. second region),
#so the controller[0] host is there

- hosts: controller[0]
  user: ansible
  sudo: True
  max_fail_percentage: 0
  tasks:
    - name: install python-keystoneclient
      apt: name=python-keystoneclient

- hosts: controller[0]
  user: ansible
  max_fail_percentage: 0
  roles:
    - os_keystone_service
  vars:
    keystone_service_name: keystone
    keystone_service_type: identity
    keystone_service_description: "OpenStack Identity"
    keystone_public_url: "http://{{ keystone_internal_ip }}:5000/v3"
    keystone_internal_url: "http://{{ keystone_internal_ip }}:5000/v3"
    keystone_admin_url: "http://{{ keystone_public_ip }}:35357/v3"
    keystone_region: "{{ keystone_region_name }}"
    keystone_projects:
      - keystone_project_name: admin
        keystone_project_description: "Admin Project"
        keystone_project_domain_name: "{{ keystone_domain_name | default('Default') }}"
      - keystone_project_name: "{{ keystone_service_project_name | default('service') }}"
        keystone_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
        keystone_project_description: "Service Project"
    keystone_users:
      - keystone_user: admin
        keystone_domain_name: "{{ keystone_domain_name | default('Default') }}"
        keystone_password: "{{ keystone_admin_password }}"
        keystone_project_name: admin
        keystone_project_domain_name: "{{ keystone_domain_name | default('Default') }}"
        keystone_role: admin
