---

- hosts: keystone
  sudo: True
  max_fail_percentage: 0
  roles:
    - common
    - os_keystone

- hosts: haproxy
  sudo: True
  max_fail_percentage: 0
  roles:
    - haproxy_service
  vars:
    haproxy_services:
      - haproxy_service_name: keystone_admin
        haproxy_backend_nodes: "{{ groups['keystone'] }}"
        haproxy_bind_hosts:
          - "{{ vip_mgmt }}"
          - "{{ vip_public }}"
        haproxy_port: 35357
        haproxy_balance_type: "{{ (keystone_ssl | default('False')) | ternary('tcp', 'http') }}"
        haproxy_balance_alg: leastconn
        haproxy_backend_options: "{{ (keystone_ssl | default('False')) | ternary([], ['forwardfor', 'httpchk', 'httplog']) }}"
      - haproxy_service_name: keystone_service
        haproxy_backend_nodes: "{{ groups['keystone'] }}"
        haproxy_bind_hosts:
          - "{{ vip_public }}"
        haproxy_port: 5000
        haproxy_balance_type: "{{ (keystone_ssl | default('False')) | ternary('tcp', 'http') }}"
        haproxy_balance_alg: leastconn
        haproxy_backend_options: "{{ (keystone_ssl | default('False')) | ternary([], ['forwardfor', 'httpchk', 'httplog']) }}"

#The plays below must run without an installed keystone (e.g. second region),
#so the controller[0] host is there

- hosts: controller[0]
  sudo: True
  max_fail_percentage: 0
  tasks:
    - name: install python-keystoneclient
      apt: name=python-keystoneclient

- hosts: controller[0]
  max_fail_percentage: 0
  roles:
    - os_keystone_service
  vars:
    keystone_service_name: keystone
    keystone_service_type: identity
    keystone_service_description: "OpenStack Identity"
    keystone_public_url: "{{ (keystone_ssl | default('False')) | ternary('https', 'http') }}://{{ keystone_internal_address }}:5000/v3"
    keystone_internal_url: "{{ (keystone_ssl | default('False')) | ternary('https', 'http') }}://{{ keystone_internal_address }}:5000/v3"
    keystone_admin_url: "{{ (keystone_ssl | default('False')) | ternary('https', 'http') }}://{{ keystone_public_address }}:35357/v3"
    keystone_region: "{{ keystone_region_name }}"
    keystone_projects:
      - keystone_project_name: admin
        keystone_project_description: "Admin Project"
        keystone_project_domain_name: "{{ keystone_domain_name | default('Default') }}"
      - keystone_project_name: "{{ keystone_service_project_name | default('service') }}"
        keystone_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
        keystone_project_description: "Service Project"
    keystone_users:
      - keystone_user: admin
        keystone_domain_name: "{{ keystone_domain_name | default('Default') }}"
        keystone_password: "{{ keystone_admin_password }}"
        keystone_project_name: admin
        keystone_project_domain_name: "{{ keystone_domain_name | default('Default') }}"
        keystone_role: admin
