---

- hosts: manila[0]
  max_fail_percentage: 0
  roles:
    - role: os_keystone_service
      keystone_service_name: manila
      keystone_service_type: share
      keystone_service_description: "OpenStack Shared Filesystem Service"
      keystone_public_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_public_address }}:8786/v1/$(tenant_id)s"
      keystone_internal_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_internal_address }}:8786/v1/$(tenant_id)s"
      keystone_admin_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_admin_address }}:8786/v1/$(tenant_id)s"
      keystone_region: "{{ keystone_region_name }}"
      keystone_users:
        - keystone_user: "{{ manila_admin_user | default('manila') }}"
          keystone_domain_name: "{{ manila_domain_name | default(keystone_domain_name) }}"
          keystone_password: "{{ manila_admin_password }}"
          keystone_project_name: "{{ keystone_service_project_name | default('service') }}"
          keystone_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
          keystone_role:
            - admin
            - service

    - role: os_keystone_service
      keystone_service_name: manilav2
      keystone_service_type: sharev2
      keystone_service_description: "OpenStack Shared Filesystem Service v2"
      keystone_public_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_public_address }}:8786/v2/$(tenant_id)s"
      keystone_internal_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_internal_address }}:8786/v2/$(tenant_id)s"
      keystone_admin_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_admin_address }}:8786/v2/$(tenant_id)s"
      keystone_region: "{{ keystone_region_name }}"

- hosts: manila
  become: True
  max_fail_percentage: 0
  roles:
    - apt

    - os_manila

    - role: apache_frontend
      apache_service_name: manila
      apache_service_ssl: "{{ os_ssl | default(False) }}"
      apache_proxyprotocol: "{{ proxyprotocol | default(False) }}"
      apache_services:
        - { port: 8786 }

- hosts: haproxy
  become: True
  max_fail_percentage: 0
  roles:
    - role: haproxy_service
      haproxy_services:
        - haproxy_service_name: manila_api
          haproxy_backend_nodes: "{{ groups['manila'] }}"
          haproxy_bind_hosts:
            - "{{ vip_mgmt }}"
            - "{{ vip_public }}"
          haproxy_port: 8786
          haproxy_balance_type: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}"
          haproxy_backend_options: "{{ (os_ssl | default(False)) | ternary(['httpchk'], ['forwardfor', 'httpchk', 'httplog']) }}"
          haproxy_proxyprotocol: "{{ proxyprotocol | default(False) }}"
