---

- hosts: mistral[0]
  max_fail_percentage: 0
  roles:
    - role: os_keystone_service
      keystone_service_name: mistral
      keystone_service_type: workflowv2
      keystone_service_description: "OpenStack Workflow Service v2"
      keystone_public_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_public_address }}:8989/v2"
      keystone_internal_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_internal_address }}:8989/v2"
      keystone_admin_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_admin_address }}:8989/v2"
      keystone_region: "{{ keystone_region_name }}"
      keystone_users:
        - keystone_user: "{{ mistral_admin_user | default('mistral') }}"
          keystone_domain_name: "{{ mistral_domain_name | default(keystone_domain_name) }}"
          keystone_password: "{{ mistral_admin_password }}"
          keystone_project_name: "{{ keystone_service_project_name | default('service') }}"
          keystone_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
          keystone_role:
            - admin
            - service

- hosts: mistral
  become: True
  max_fail_percentage: 0
  roles:
    - apt

    - os_mistral

    - role: apache_frontend
      apache_service_name: mistral
      apache_service_ssl: "{{ os_ssl | default(False) }}"
      apache_proxyprotocol: "{{ proxyprotocol | default(False) }}"
      apache_services:
        - { port: 8989 }

- hosts: haproxy
  become: True
  max_fail_percentage: 0
  roles:
    - role: haproxy_service
      haproxy_services:
        - haproxy_service_name: mistral_api
          haproxy_backend_nodes: "{{ groups['mistral'] }}"
          haproxy_bind_hosts:
            - "{{ vip_mgmt }}"
            - "{{ vip_public }}"
          haproxy_port: 8989
          haproxy_balance_type: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}"
          haproxy_backend_options: "{{ (os_ssl | default(False)) | ternary(['httpchk'], ['forwardfor', 'httpchk', 'httplog']) }}"
          haproxy_proxyprotocol: "{{ proxyprotocol | default(False) }}"
