---

- hosts: murano[0]
  max_fail_percentage: 0
  roles:
    - os_keystone_service
  vars:
    keystone_service_name: murano
    keystone_service_type: application-catalog
    keystone_service_description: "OpenStack Application Catalog Service"
    keystone_public_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_public_address }}:8082"
    keystone_internal_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_internal_address }}:8082"
    keystone_admin_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_admin_address }}:8082"
    keystone_region: "{{ keystone_region_name }}"
    keystone_users:
      - keystone_user: "{{ murano_admin_user | default('murano') }}"
        keystone_domain_name: "{{ murano_domain_name | default(keystone_domain_name) }}"
        keystone_password: "{{ murano_admin_password }}"
        keystone_project_name: "{{ keystone_service_project_name | default('service') }}"
        keystone_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
        keystone_role: admin

- hosts: murano
  sudo: True
  max_fail_percentage: 0
  roles:
    - common
    - os_murano

- hosts: murano
  sudo: True
  max_fail_percentage: 0
  roles:
    - apache_frontend
  vars:
    service_name: murano
    service_ssl: "{{ os_ssl | default(False) }}"
    services:
      - { port: 8082 }

- hosts: haproxy
  sudo: True
  max_fail_percentage: 0
  roles:
    - haproxy_service
  vars:
    haproxy_services:
      - haproxy_service_name: murano_api
        haproxy_backend_nodes: "{{ groups['murano'] }}"
        haproxy_bind_hosts:
          - "{{ vip_mgmt }}"
          - "{{ vip_public }}"
        haproxy_port: 8082
        haproxy_balance_type: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}"
        haproxy_backend_options: "{{ (os_ssl | default(False)) | ternary(['httpchk'], ['forwardfor', 'httpchk', 'httplog']) }}"
