---

- hosts: magnum[0]
  max_fail_percentage: 0
  roles:
    - role: os_keystone_service
      keystone_service_name: magnum
      keystone_service_type: container
      keystone_service_description: "OpenStack Container Service"
      keystone_public_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_public_address }}:9511/v1"
      keystone_internal_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_internal_address }}:9511/v1"
      keystone_admin_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_admin_address }}:9511/v1"
      keystone_region: "{{ keystone_region_name }}"
      keystone_users:
        - keystone_user: "{{ magnum_admin_user | default('magnum') }}"
          keystone_domain_name: "{{ magnum_domain_name | default(keystone_domain_name) }}"
          keystone_password: "{{ magnum_admin_password }}"
          keystone_project_name: "{{ keystone_service_project_name | default('service') }}"
          keystone_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
          keystone_role: admin
        - keystone_user: "{{ magnum_domain_admin | default('magnum_trustee') }}"
          keystone_domain_name: "{{ magnum_domain | default('magnum') }}"
          keystone_password: "{{ magnum_domain_admin_password }}"
          keystone_project_name:
          keystone_project_domain_name:
          keystone_role: admin
- hosts: magnum
  become: True
  max_fail_percentage: 0
  roles:
    - common

    - os_magnum

    - role: apache_frontend
      apache_service_name: magnum
      apache_service_ssl: "{{ os_ssl | default(False) }}"
      apache_services:
        - { port: 9511 }

- hosts: haproxy
  become: True
  max_fail_percentage: 0
  roles:
    - role: haproxy_service
      haproxy_services:
        - haproxy_service_name: magnum_api
          haproxy_backend_nodes: "{{ groups['magnum'] }}"
          haproxy_bind_hosts:
            - "{{ vip_mgmt }}"
            - "{{ vip_public }}"
          haproxy_port: 9511
          haproxy_balance_type: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}"
          haproxy_backend_options: "{{ (os_ssl | default(False)) | ternary(['httpchk'], ['forwardfor', 'httpchk', 'httplog']) }}"
