---

- hosts: neutron_controller[0]
  max_fail_percentage: 0
  roles:
    - os_keystone_service
  vars:
    keystone_service_name: neutron
    keystone_service_type: network
    keystone_service_description: "OpenStack Networking Service"
    keystone_public_url: "http://{{ vip_public }}:9696"
    keystone_internal_url: "http://{{ vip_mgmt }}:9696"
    keystone_admin_url: "http://{{ vip_mgmt }}:9696"
    keystone_region: "{{ keystone_region_name }}"
    keystone_users:
      - keystone_user: "{{ neutron_admin_user | default('neutron') }}"
        keystone_domain_name: "{{ neutron_domain_name | default(keystone_domain_name) }}"
        keystone_password: "{{ neutron_admin_password }}"
        keystone_project_name: "{{ keystone_service_project_name | default('service') }}"
        keystone_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
        keystone_role: admin

- hosts:
    - neutron_controller
    - neutron_compute
  sudo: True
  max_fail_percentage: 0
  roles:
    - common
    - os_neutron

- hosts: neutron_controller
  sudo: True
  max_fail_percentage: 0
  roles:
    - apache_frontend
  vars:
    service_name: neutron
    service_ports:
      - 9696

- hosts: haproxy
  sudo: True
  max_fail_percentage: 0
  roles:
    - haproxy_service
  vars:
    haproxy_services:
      - haproxy_service_name: neutron_server
        haproxy_backend_nodes: "{{ groups['neutron_controller'] }}"
        haproxy_bind_hosts:
          - "{{ vip_mgmt }}"
          - "{{ vip_public }}"
        haproxy_port: 9696
        haproxy_balance_type: http
        haproxy_backend_options:
         - forwardfor
         - httpchk
         - httplog
