---

- hosts: neutron_controller[0]
  max_fail_percentage: 0
  roles:
    - role: os_keystone_service
      keystone_service_name: neutron
      keystone_service_type: network
      keystone_service_description: "OpenStack Networking Service"
      keystone_public_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_public_address }}:9696"
      keystone_internal_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_internal_address }}:9696"
      keystone_admin_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_admin_address }}:9696"
      keystone_region: "{{ keystone_region_name }}"
      keystone_users:
        - keystone_user: "{{ neutron_admin_user | default('neutron') }}"
          keystone_domain_name: "{{ neutron_domain_name | default(keystone_domain_name) }}"
          keystone_password: "{{ neutron_admin_password }}"
          keystone_project_name: "{{ keystone_service_project_name | default('service') }}"
          keystone_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
          keystone_role:
            - admin
            - service

- hosts:
    - neutron_controller
    - neutron_l3
    - neutron_l2
  become: True
  max_fail_percentage: 0
  roles:
    - apt
    - os_neutron

- hosts: neutron_controller
  become: True
  max_fail_percentage: 0
  roles:
    - role: apache_frontend
      apache_service_name: neutron
      apache_service_ssl: "{{ os_ssl | default(False) }}"
      apache_proxyprotocol: "{{ proxyprotocol | default(False) }}"
      apache_services:
        - { port: 9696 }

- hosts: haproxy
  become: True
  max_fail_percentage: 0
  roles:
    - role: haproxy_service
      haproxy_services:
        - haproxy_service_name: neutron_server
          haproxy_backend_nodes: "{{ groups['neutron_controller'] }}"
          haproxy_bind_hosts:
            - "{{ vip_mgmt }}"
            - "{{ vip_public }}"
          haproxy_port: 9696
          haproxy_balance_type: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}"
          haproxy_backend_options: "{{ (os_ssl | default(False)) | ternary(['httpchk'], ['forwardfor', 'httpchk', 'httplog']) }}"
          haproxy_proxyprotocol: "{{ proxyprotocol | default(False) }}"
