---

- hosts: neutron_controller[0]
  user: ansible
  max_fail_percentage: 0
  roles:
    - os_keystone_service
  vars:
    keystone_service_name: neutron
    keystone_service_type: network
    keystone_service_description: "OpenStack Networking Service"
    keystone_public_url: "http://{{ keystone_internal_ip }}:9696"
    keystone_internal_url: "http://{{ keystone_internal_ip }}:9696"
    keystone_admin_url: "http://{{ keystone_public_ip }}:9696"
    keystone_region: "{{ keystone_region_name }}"
    keystone_projects:
      - keystone_project_name: service
        keystone_project_description: "Service Project"
        keystone_user: neutron
        keystone_domain: "{{ keystone_domain_id }}"
        keystone_password: "{{ neutron_admin_password }}"
        keystone_role: admin

- hosts:
    - neutron_controller
    - neutron_compute
  user: ansible
  sudo: True
  max_fail_percentage: 0
  roles:
    - common
    - os_neutron

- hosts: haproxy
  user: ansible
  sudo: True
  max_fail_percentage: 0
  roles:
    - haproxy_service
  vars:
    haproxy_services:
      - haproxy_service_name: neutron_server
        haproxy_backend_nodes: "{{ groups['neutron_controller'] }}"
        haproxy_bind_hosts:
          - "{{ vip_mgmt }}"
          - "{{ vip_public }}"
        haproxy_port: 9696
        haproxy_balance_type: http
        haproxy_backend_options:
         - forwardfor
         - httpchk
         - httplog
