---

- hosts: senlin[0]
  max_fail_percentage: 0
  roles:
    - role: os_keystone_service
      keystone_service_name: senlin
      keystone_service_type: clustering
      keystone_service_description: "OpenStack Clustering Service"
      keystone_public_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_public_address }}:8778"
      keystone_internal_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_internal_address }}:8778"
      keystone_admin_url: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}://{{ os_admin_address }}:8778"
      keystone_region: "{{ keystone_region_name }}"
      keystone_users:
        - keystone_user: "{{ senlin_admin_user | default('senlin') }}"
          keystone_domain_name: "{{ senlin_domain_name | default(keystone_domain_name) }}"
          keystone_password: "{{ senlin_admin_password }}"
          keystone_project_name: "{{ keystone_service_project_name | default('service') }}"
          keystone_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
          keystone_role: admin

- hosts: senlin
  become: True
  max_fail_percentage: 0
  roles:
    - common

    - os_senlin

    - role: apache_frontend
      apache_service_name: senlin
      apache_service_ssl: "{{ os_ssl | default(False) }}"
      apache_services:
        - { port: 8778 }

- hosts: haproxy
  become: True
  max_fail_percentage: 0
  roles:
    - role: haproxy_service
      haproxy_services:
        - haproxy_service_name: senlin_api
          haproxy_backend_nodes: "{{ groups['senlin'] }}"
          haproxy_bind_hosts:
            - "{{ vip_mgmt }}"
            - "{{ vip_public }}"
          haproxy_port: 8778
          haproxy_balance_type: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}"
          haproxy_backend_options: "{{ (os_ssl | default(False)) | ternary(['httpchk'], ['forwardfor', 'httpchk', 'httplog']) }}"
