---

- hosts: pacemaker
  become: True
  max_fail_percentage: 0
  roles:
    - apt
  pre_tasks:
    - name: check for Ansible version > 2.0.1
      local_action: assert that="{{ ansible_version.string is version_compare('2.0.1', '>=') }}"
      run_once: True
      become: False

- hosts: pacemaker
  become: True
  max_fail_percentage: 0
  serial: 1
  tasks:
    - name: upgrade pacemaker
      apt: name={{ item }} state=latest
      with_items:
        - corosync
        - pacemaker-common
        - pacemaker
      notify: restart pacemaker

    - meta: flush_handlers

    - name: wait until the cluster is active
      command: /usr/sbin/crm_mon -1
      register: pacemaker_status
      until: 'pacemaker_status.stdout.find("Current DC: NONE") == -1 and pacemaker_status.rc == 0'
      failed_when: False
      changed_when: False
      retries: 10
      delay: 5

  handlers:
    - name: restart pacemaker
      service: name={{ item }} state=restarted enabled=yes
      with_items:
        - corosync
        - pacemaker
