---

- hosts: rabbitmq
  become: True
  max_fail_percentage: 0
  roles:
    - apt

    - role: hosts
      hosts: "{{ groups['rabbitmq'] }}"

    - role: rabbitmq
      rabbitmq_hosts: "{{ groups['rabbitmq'] }}"
      rabbitmq_listen_addresses:
        - "{{ ip.mgmt }}"
      rabbitmq_cookie: "{{ rabbitmq_erlang_cookie }}"
      rabbitmq_password: "{{ rabbitmq_admin_password }}"
