---

- hosts: mongodb
  become: True
  max_fail_percentage: 0
  tasks:
    - name: determine the primary node
      command: mongo --quiet --eval 'rs.isMaster().ismaster'
      register: mongo_master
      changed_when: False
      when: syslog_use_mongodb | default(False)

    - name: create syslog mongo user
      mongodb_user: login_user=admin login_password={{ mongodb_admin_password }} database=syslog name=syslog password={{ syslog_db_password }}
      when: syslog_use_mongodb | default(False) and mongo_master.stdout == 'true'

- hosts: syslog-ng
  become: True
  max_fail_percentage: 0
  roles:
    - role: common
      apt_extra_repos:
        - { name: "syslog-ng", repo: "http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng-3.6/xUbuntu_14.04/ ./" }
      apt_extra_keys:
        - { keyurl: "http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng-3.6/xUbuntu_14.04/Release.key" }
      when: ansible_distribution_version | version_compare('14.04', '=')

    - role: common
      apt_extra_repos:
        - { name: "syslog-ng", repo: "http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng-3.6/xUbuntu_15.04/ ./" }
      apt_extra_keys:
        - { keyurl: "http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng-3.6/xUbuntu_15.04/Release.key" }
      when: ansible_distribution_version | version_compare('14.04', '>')

    - role: syslog-ng
