trove_admin_user: trove
trove_domain_name: "{{ keystone_domain_name }}"
trove_project_domain_name: "{{ trove_domain_name }}"
trove_project_name: trove

trove_datastores:
 - { datastore: "mysql", version: "5.6", image: "/etc/openstack_deploy/trove-mysql.qcow2", manager: "mysql", packages: "mysql-server-5.6" }

keystone_proto: "{{ (keystone_ssl | default(False)) | ternary('https', 'http') }}"
os_proto: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}"
ssl_insecure: False
SSLCACertificateFileSource:
SSLCACertificateFile: "{{ (SSLCACertificateFileSource is not none and SSLCACertificateFileSource | trim != '') | ternary('/etc/ssl/certs/openstack.ca.crt','') }}"
