---

- name: signal apache to reload
  file: dest=/run/apache2.reload state=touch

- name: restart aodh
  service: name={{ item }} state=restarted
  with_items:
    - aodh-evaluator
    - aodh-notifier
    - aodh-listener
