---

octavia_db_user: octavia
octavia_mysql_server: "{{ vip_mgmt }}"
octavia_db: octavia
octavia_rabbit_vhost: octavia
octavia_rabbit_user: octavia
octavia_admin_user: octavia
octavia_domain_name: "{{ keystone_domain_name }}"
octavia_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
octavia_project_name: "{{ keystone_service_project_name | default('service') }}"

#octavia_controller_workers: "{{ (ansible_processor_vcpus + 1) // 2 }}"
octavia_controller_workers: 1
#SIGNLE, ACTIVE_STANDBY
octavia_loadbalancer_topology: ACTIVE_STANDBY

octavia_notifications: "{{ notifications_enable | default(False) }}"

octavia_syslog_use: "{{ syslog_use | default(False) }}"

octavia_debug: False

keystone_proto: "{{ (keystone_ssl | default(False)) | ternary('https', 'http') }}"
os_proto: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}"
ssl_insecure: False
SSLCACertificateFileSource:
SSLCACertificateFile: "{{ (SSLCACertificateFileSource is not none and SSLCACertificateFileSource | trim != '') | ternary('/etc/ssl/certs/openstack.ca.crt','') }}"
