- name: setup apt repo(s)
  copy: content='deb {{ item.repo }}\n' dest=/etc/apt/sources.list.d/{{ item.name }}.list
  with_items:
    - "{{ apt_repos }}"
    - "{{ apt_extra_repos }}"
  notify: update apt cache

- name: add apt key(s)
  apt_key: keyserver='{{ item.keyserver }}' id='{{ item.keyid | default('') }}'
  with_items:
    - "{{ apt_keys }}"
    - "{{ apt_extra_keys }}"
  when: item.keyserver is defined
  notify: update apt cache

- name: add apt key(s)
  apt_key: id='{{ item.keyid | default('') }}' url='{{ item.keyurl }}'
  with_items:
    - "{{ apt_keys }}"
    - "{{ apt_extra_keys }}"
  when: item.keyurl is defined
  notify: update apt cache

- meta: flush_handlers

- name: update apt cache
  apt: update_cache=yes cache_valid_time={{ apt_cache_valid_time }}
