---

senlin_db_user: senlin
senlin_mysql_server: "{{ vip_mgmt }}"
senlin_db: senlin
senlin_rabbit_vhost: senlin
senlin_rabbit_user: senlin
senlin_admin_user: senlin
senlin_domain_name: "{{ keystone_domain_name }}"
senlin_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
senlin_project_name: "{{ keystone_service_project_name | default('service') }}"

senlin_api_workers: "{{ (ansible_processor_vcpus + 1) // 2 }}"
senlin_engine_workers: "{{ (ansible_processor_vcpus + 1) // 2 }}"

senlin_syslog_use: "{{ syslog_use | default(False) }}"

senlin_debug: False

keystone_proto: "{{ (keystone_ssl | default(False)) | ternary('https', 'http') }}"
ssl_insecure: False
SSLCACertificateFileSource:
SSLCACertificateFile: "{{ (SSLCACertificateFileSource is not none and SSLCACertificateFileSource | trim != '') | ternary('/etc/ssl/certs/openstack.ca.crt','') }}"
