---

glance_db_user: glance
glance_mysql_server: "{{ vip_mgmt }}"
glance_db: glance
glance_rabbit_vhost: glance
glance_rabbit_user: glance
glance_admin_user: glance
glance_domain_name: "{{ keystone_domain_name }}"
glance_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
glance_project_name: "{{ keystone_service_project_name | default('service') }}"

glance_api_workers: "{{ (ansible_processor_vcpus + 1) // 2 }}"
glance_registry_workers: "{{ (ansible_processor_vcpus + 1) // 2 }}"

ceph_cluster_name: ceph

glance_backend: files
glance_ceph_pool: images
glance_ceph_user: glance

glance_syslog_use: "{{ syslog_use | default(False) }}"

glance_debug: False

keystone_proto: "{{ (keystone_ssl | default(False)) | ternary('https', 'http') }}"
os_proto: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}"
ssl_insecure: False
SSLCACertificateFileSource:
SSLCACertificateFile: "{{ (SSLCACertificateFileSource is not none and SSLCACertificateFileSource | trim != '') | ternary('/etc/ssl/certs/openstack.ca.crt','') }}"
