---

aodh_db_user: aodh
aodh_mysql_server: "{{ vip_mgmt }}"
aodh_db: aodh
aodh_rabbit_vhost: aodh
aodh_rabbit_user: aodh
aodh_admin_user: aodh
aodh_domain_name: "{{ keystone_domain_name }}"
aodh_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
aodh_project_name: "{{ keystone_service_project_name | default('service') }}"

aodh_syslog_use: "{{ syslog_use | default(False) }}"

aodh_debug: False

keystone_proto: "{{ (keystone_ssl | default(False)) | ternary('https', 'http') }}"
ssl_insecure: False
SSLCACertificateFileSource:
SSLCACertificateFile: "{{ (SSLCACertificateFileSource is not none and SSLCACertificateFileSource | trim != '') | ternary('/etc/ssl/certs/openstack.ca.crt','') }}"
