---

tempest_git_repo: https://git.openstack.org/openstack/tempest
tempest_version: master
tempest_dest: "{{ ansible_env.HOME }}/tempest"
tempest_lock_path: "{{ ansible_env.HOME }}/tempest/lock"
tempest_images_dest: "{{ ansible_env.HOME }}/tempest_images"
tempest_images_url: http://download.cirros-cloud.net/0.3.4
tempest_image_file: cirros-0.3.4-x86_64-disk.img
tempest_image_ari_img_file: cirros-0.3.4-x86_64-initramfs
tempest_image_aki_img_file: cirros-0.3.4-x86_64-kernel

cirros_image_url: http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img
cirros_ssh_user: cirros

external_net_name: ext-net
external_net_type: vlan
external_physical_network: vlan
external_net_segmentation_id: 996
external_subnet_cidr: 10.97.37.0/25
external_subnet_gateway_ip: 10.97.37.126
external_subnet_allocation_start: 10.97.37.1
external_subnet_allocation_end: 10.97.37.125

neutron_vpnaas_type:
neutron_api_extensions:
  - dns-integration
  - ext-gw-mode
  - binding
  - agent
  - subnet_allocation
  - l3_agent_scheduler
  - external-net
  - flavors
  - fwaasrouterinsertion
  - net-mtu
  - quotas
  - l3-ha
  - provider
  - multi-provider
  - lbaas
  - extraroute
  - lbaas_agent_scheduler
  - fwaas
  - router
  - extra_dhcp_opt
  - service-type
  - security-group
  - dhcp_agent_scheduler
  - rbac-policies
  - port-security
  - allowed-address-pairs

tenant_network_cidr: 10.100.0.0/16

heat_stack_owner_project: demo
heat_stack_owner_user: demo
heat_stack_owner_password: demo

swift_api_extensions:
  - bulk_delete
  - container_quotas
  - bulk_upload
  - ratelimit
  - slo
  - account_quotas
  - swift

keystone_proto: "{{ (keystone_ssl | default(False)) | ternary('https', 'http') }}"
ssl_insecure: False
SSLCACertificateFileSource:
