---

rgw_keystone_accepted_roles: "Member, admin, swiftoperator"

keystone_proto: "{{ (keystone_ssl | default(False)) | ternary('https', 'http') }}"
ssl_insecure: False

radosgw_keystone: True
radosgw_port: 8080

radosgw_admin_user: radosgw
radosgw_domain_name: "{{ keystone_domain_name }}"
radosgw_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
radosgw_project_name: "{{ keystone_service_project_name | default('service') }}"
