---

- hosts:
    - ceph_monitor
    - ceph_osd
    - ceph_radosgw
    - pacemaker
    - haproxy
    - memcached
    - rabbitmq
    - galera
    - mongodb
    - keystone
    - swift_proxy
    - swift_storage
    - glance
    - horizon
    - nova_controller
    - nova_compute
    - neutron_controller
    - neutron_compute
    - ceilometer_controller
    - ceilometer_compute
    - heat
    - trove
    - cinder
    - murano
    - sahara
    - barbican
    - ironic
    - nova_compute
    - neutron_compute
    - ceilometer_compute
    - cinder_volume
  become: True
  max_fail_percentage: 0
  roles:
    - common
    - nrpe

- hosts: ceph_monitor
  become: True
  max_fail_percentage: 0
  roles:
    - role: ceph_client
  vars:
    ceph_users:
      - cluster_name: "{{ ceph_cluster_name | default('ceph') }}"
        monitors: "{{ ceph_monitors | default(groups['ceph_monitor']) }}"
        user: nagios
        key:
        rights: "mon 'allow r'"
        keyring_owner: nagios
