---

- hosts:
    - ceph_monitor
    - ceph_osd
    - ceph_radosgw
    - pacemaker
    - haproxy
    - memcached
    - rabbitmq
    - galera
    - mongodb
    - keystone
    - swift_proxy
    - swift_storage
    - glance
    - horizon
    - nova_controller
    - nova_compute
    - neutron_controller
    - neutron_compute
    - ceilometer_controller
    - ceilometer_compute
    - heat
    - trove
    - cinder
    - murano
    - sahara
    - barbican
    - ironic
    - nova_compute
    - neutron_compute
    - ceilometer_compute
    - cinder_volume
  become: True
  max_fail_percentage: 0
  roles:
    - common
    - nrpe

- hosts: ceph_monitor
  become: True
  max_fail_percentage: 0
  roles:
    - role: ceph_client
  vars:
    ceph_user: nagios
    ceph_rights: "mon 'allow r'"
    ceph_keyring_owner: nagios
