---

- name: create cloudkitty vhost in rabbitmq
  rabbitmq_vhost: node="rabbit@{{ groups['rabbitmq'][0] }}" name="{{ cloudkitty_rabbit_vhost }}"
  delegate_to: "{{ groups['rabbitmq'][0] }}"
  run_once: True

- name: create cloudkitty user in rabbitmq
  rabbitmq_user: node="rabbit@{{ groups['rabbitmq'][0] }}"
      user="{{ cloudkitty_rabbit_user }}" password="{{ cloudkitty_rabbit_password }}"
      vhost="{{ cloudkitty_rabbit_vhost }}"
      configure_priv=".*" read_priv=".*" write_priv=".*"
  delegate_to: "{{ groups['rabbitmq'][0] }}"
  run_once: True

- name: ensure the cloudkitty vhost contains the HA policy
  rabbitmq_policy:
    node: "rabbit@{{ groups['rabbitmq'][0] }}"
    vhost: "{{ cloudkitty_rabbit_vhost }}"
    name: HA
    pattern: '.*'
    tags:
      "ha-mode": "all"
      "ha-sync-mode": "automatic"
  delegate_to: "{{ groups['rabbitmq'][0] }}"
  run_once: True

- name: install CA certificate
  copy: src="{{ SSLCACertificateFileSource }}" dest="{{ SSLCACertificateFile }}" owner=root group=root mode=0644
  when: SSLCACertificateFile != ''

- name: mask autostarting of cloudkitty
  service_mask: name={{ item }} state=masked
  with_items:
    - cloudkitty-api
    - cloudkitty-processor

- name: install cloudkitty
  apt:
    name:
    - cloudkitty-api
    - cloudkitty-processor

- name: create cloudkitty database
  mysql_db: name={{ cloudkitty_db }}
    login_host={{ cloudkitty_mysql_server }} login_user=root login_password={{ mysql_root_password }}
    state=present
  run_once: True

- name: create cloudkitty database user
  mysql_user: name={{ cloudkitty_db_user }} password={{ cloudkitty_db_password }} host={{ item }} priv={{ cloudkitty_db }}.*:ALL
    login_host={{ cloudkitty_mysql_server }} login_user=root login_password={{ mysql_root_password }}
    state=present
  run_once: True
  with_items:
    - localhost
    - '%'

- name: install cloudkitty configs
  template: src=cloudkitty.conf.j2 dest=/etc/cloudkitty/cloudkitty.conf owner=cloudkitty group=root mode=0460
  notify: restart cloudkitty

- name: install /etc/default/cloudkitty-api
  copy: content='DAEMON_ARGS="--master --paste-logger --processes {{ cloudkitty_api_workers }} --die-on-term --logto /var/log/cloudkitty/cloudkitty-api.log --http-socket 127.0.0.1:8889 --wsgi-file /usr/bin/cloudkitty-api"\n'
        dest=/etc/default/cloudkitty-api owner=root group=root mode=0644

- name: sync cloudkitty db
  command: su cloudkitty -s /bin/sh -c "/usr/bin/cloudkitty-dbsync upgrade"
  register: db_sync
  changed_when: '"Running upgrade" in db_sync.stderr'
  run_once: True

- name: unmask autostarting of cloudkitty
  service_mask: name={{ item }} state=unmasked
  with_items:
    - cloudkitty-api
    - cloudkitty-processor

- meta: flush_handlers

- name: ensure cloudkitty is started
  service: name={{ item }} state=started enabled=yes
  with_items:
    - cloudkitty-api
    - cloudkitty-processor
