---

ironic_db_user: ironic
ironic_mysql_server: "{{ vip_mgmt }}"
ironic_db: ironic
ironic_rabbit_vhost: ironic
ironic_rabbit_user: ironic
ironic_admin_user: ironic
ironic_domain_name: "{{ keystone_domain_name }}"
ironic_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
ironic_project_name: "{{ keystone_service_project_name | default('service') }}"

ironic_api_workers: "{{ (ansible_processor_vcpus + 1) // 2 }}"

ironic_deploy_kernel_path: ironic-deploy.kernel
ironic_deploy_initramfs_path: ironic-deploy.initramfs

ironic_default_network_interface: flat
ironic_enabled_network_interfaces: noop,flat,neutron
ironic_cleaning_network: ironic-net
ironic_provisioning_network: ironic-net
ironic_automated_clean: False
#Default is None, so conductor get it from Keystone
ironic_api_url:

ironic_notifications: "{{ notifications_enable | default(False) }}"

ironic_syslog_use: "{{ syslog_use | default(False) }}"

ironic_debug: False

keystone_proto: "{{ (keystone_ssl | default(False)) | ternary('https', 'http') }}"
os_proto: "{{ (os_ssl | default(False)) | ternary('https', 'http') }}"
ssl_insecure: False
SSLCACertificateFileSource:
SSLCACertificateFile: "{{ (SSLCACertificateFileSource is not none and SSLCACertificateFileSource | trim != '') | ternary('/etc/ssl/certs/openstack.ca.crt','') }}"
