---

apt_repos:
  - { name: "cloudarchive-mitaka", repo: "http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/mitaka main" }

apt_extra_repos: []

apt_keys:
  - { keyserver: "keyserver.ubuntu.com", keyid: "5EDB1B62EC4926EA" }

apt_extra_keys: []

apt_cache_valid_time: 1800
