ceph_cluster_name: ceph
ceph_osd_bluestore: True

ceph_osd_journal_size: 10000
ceph_bluestore_block_size: 0
ceph_filestore_xattr_use_omap: true
ceph_osd_pool_default_size: 3
ceph_osd_pool_default_min_size: 0
ceph_osd_crush_chooseleaf_type: 1
ceph_osd_crush_update_on_start: True

#extra key-value settings to apply on OSDs
#example:
# ceph_osd_extra_settings:
#   'osd max backfills': 1
#   'osd op threads': 2
ceph_osd_extra_settings: {}
