ceph_cluster_name: ceph
ceph_osd_journal_size: 10000
ceph_filestore_xattr_use_omap: true
ceph_osd_pool_default_size: 3
ceph_osd_pool_default_min_size: 0
ceph_osd_pool_default_pg_num: 64
ceph_osd_pool_default_pgp_num: 64
ceph_osd_crush_chooseleaf_type: 1
