---

swift_db_user: swift
swift_mysql_server: "{{ vip_mgmt }}"
swift_db: swift
swift_rabbit_vhost: swift
swift_rabbit_user: swift
swift_admin_user: swift
swift_domain_name: "{{ keystone_domain_name }}"
swift_project_domain_name: "{{ keystone_service_project_domain_name | default(keystone_domain_name) }}"
swift_project_name: "{{ keystone_service_project_name | default('service') }}"

swift_syslog_use: "{{ syslog_use | default(False) }}"

swift_part_power: 12
swift_replicas: 3
swift_min_part_hours: 1
swift_operator_roles: admin,user,member,_Member_,ResellerAdmin

swift_pipeline:
 - catch_errors
 - gatekeeper
 - healthcheck
 - proxy-logging
 - cache
 - container_sync
 - bulk
 - ratelimit
 - authtoken
 - keystoneauth
 - container-quotas
 - account-quotas
 - slo
 - dlo
 - versioned_writes
 - proxy-logging
 - "{{ (groups['ceilometer_controller'] | count > 0) | ternary('ceilometer', '') }}"
 - proxy-server

keystone_proto: "{{ (keystone_ssl | default(False)) | ternary('https', 'http') }}"
ssl_insecure: False
SSLCACertificateFileSource:
SSLCACertificateFile: "{{ (SSLCACertificateFileSource is not none and SSLCACertificateFileSource | trim != '') | ternary('/etc/ssl/certs/openstack.ca.crt','') }}"
