- name: restart ironic
  service: name={{ item }} state=restarted
  with_items:
    - ironic-api
    - ironic-conductor

- name: restart tftp
  service: name={{ item }} state=restarted
  with_items:
    - tftpd-hpa
