---

keystone_db_user: keystone
keystone_mysql_server: "{{ vip_mgmt }}"
keystone_db: keystone
keystone_rabbit_vhost: keystone
keystone_rabbit_user: keystone

keystone_memcache_dead_retry: 60
keystone_memcache_socket_timeout: 1
keystone_memcache_pool_maxsize: 1000
keystone_memcache_pool_unused_timeout: 60

keystone_token_expiration: 3600
#uuid or fernet
keystone_token_provider: uuid
#max. active fernet keys
keystone_max_active_keys: 3

keystone_syslog_use: "{{ syslog_use | default(False) }}"
