---

keystone_db_user: keystone
keystone_mysql_server: "{{ vip_mgmt }}"
keystone_db: keystone
keystone_rabbit_user: keystone

keystone_processes: "{{ ansible_processor_vcpus }}"

keystone_syslog_use: "{{ syslog_use | default(False) }}"

keystone_ssl: False
SSLCertificateKeyFile: /etc/ssl/private/openstack.key
SSLCertificateFile: /etc/ssl/certs/openstack.crt
